export type TourAudience = "all" | "contributor" | "reviewer" | "admin";

export interface TourFeature {
  icon: string;
  color: string;
  bgColor: string;
  titleKey?: string;
  detailKey?: string;
  title?: string;
  detail?: string;
}

export interface MobileTourConfig {
  route: string;
  audience: TourAudience;
  heroIcon: string;
  heroColor: string;
  heroBg: string;
  titleKey?: string;
  subtitleKey?: string;
  title?: string;
  subtitle?: string;
  features: TourFeature[];
}

const defaultFeature = (label: string): TourFeature => ({
  icon: "sparkles",
  color: "#3b82f6",
  bgColor: "#dbeafe",
  title: "How to use this screen",
  detail: label,
});

export const MOBILE_TOUR_REGISTRY = {
  welcome: {
    route: "/(tabs)/learn",
    audience: "all",
    heroIcon: "hand.wave.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Welcome to Beeli",
    subtitle: "Quickly discover everything you can do in the app.",
    features: [
      {
        icon: "book.fill",
        color: "#2563eb",
        bgColor: "#dbeafe",
        title: "Learn",
        detail: "Follow structured lessons, track progress, and keep your streak alive.",
      },
      {
        icon: "sparkles",
        color: "#7c3aed",
        bgColor: "#ede9fe",
        title: "Practice",
        detail: "Improve with quizzes, matching games, and multiplayer challenges.",
      },
      {
        icon: "pencil.and.list.clipboard",
        color: "#0ea5e9",
        bgColor: "#e0f2fe",
        title: "Journal",
        detail: "Write reflections to retain vocabulary and build learning momentum.",
      },
      {
        icon: "newspaper.fill",
        color: "#9333ea",
        bgColor: "#f3e8ff",
        title: "Community",
        detail: "Share progress, discover posts, and engage with other learners.",
      },
      {
        icon: "person.fill",
        color: "#059669",
        bgColor: "#d1fae5",
        title: "Profile",
        detail: "See your stats, open settings, and access advanced features.",
      },
    ],
  },
  learn: {
    route: "/(tabs)/learn",
    audience: "all",
    heroIcon: "book.fill",
    heroColor: "#3b82f6",
    heroBg: "#dbeafe",
    titleKey: "onboarding.learnTourTitle",
    subtitleKey: "onboarding.learnTourSubtitle",
    features: [
      {
        icon: "book.fill",
        color: "#3b82f6",
        bgColor: "#dbeafe",
        titleKey: "onboarding.learnTourCourses",
        detailKey: "onboarding.learnTourCoursesDetail",
      },
      {
        icon: "speaker.wave.2.fill",
        color: "#10b981",
        bgColor: "#d1fae5",
        titleKey: "onboarding.learnTourAudio",
        detailKey: "onboarding.learnTourAudioDetail",
      },
      {
        icon: "chart.bar.fill",
        color: "#f59e0b",
        bgColor: "#fef3c7",
        titleKey: "onboarding.learnTourProgress",
        detailKey: "onboarding.learnTourProgressDetail",
      },
    ],
  },
  practice: {
    route: "/(tabs)/listen",
    audience: "all",
    heroIcon: "sparkles",
    heroColor: "#8b5cf6",
    heroBg: "#ede9fe",
    titleKey: "onboarding.practiceTourTitle",
    subtitleKey: "onboarding.practiceTourSubtitle",
    features: [
      {
        icon: "trophy.fill",
        color: "#3b82f6",
        bgColor: "#dbeafe",
        titleKey: "onboarding.practiceTourQuiz",
        detailKey: "onboarding.practiceTourQuizDetail",
      },
      {
        icon: "rectangle.grid.2x2",
        color: "#8b5cf6",
        bgColor: "#ede9fe",
        titleKey: "onboarding.practiceTourMatching",
        detailKey: "onboarding.practiceTourMatchingDetail",
      },
      {
        icon: "flame.fill",
        color: "#f59e0b",
        bgColor: "#fef3c7",
        titleKey: "onboarding.practiceTourDaily",
        detailKey: "onboarding.practiceTourDailyDetail",
      },
      {
        icon: "person.2.fill",
        color: "#ef4444",
        bgColor: "#fee2e2",
        titleKey: "onboarding.practiceTourMultiplayer",
        detailKey: "onboarding.practiceTourMultiplayerDetail",
      },
    ],
  },
  journal: {
    route: "/(tabs)/journal",
    audience: "all",
    heroIcon: "pencil.and.list.clipboard",
    heroColor: "#3b82f6",
    heroBg: "#dbeafe",
    titleKey: "onboarding.journalTourTitle",
    subtitleKey: "onboarding.journalTourSubtitle",
    features: [
      {
        icon: "pencil.and.list.clipboard",
        color: "#3b82f6",
        bgColor: "#dbeafe",
        titleKey: "onboarding.journalTourWrite",
        detailKey: "onboarding.journalTourWriteDetail",
      },
      {
        icon: "clock.arrow.circlepath",
        color: "#10b981",
        bgColor: "#d1fae5",
        titleKey: "onboarding.journalTourRevisit",
        detailKey: "onboarding.journalTourRevisitDetail",
      },
    ],
  },
  feed: {
    route: "/(tabs)/feed",
    audience: "all",
    heroIcon: "newspaper.fill",
    heroColor: "#8b5cf6",
    heroBg: "#ede9fe",
    titleKey: "onboarding.feedTourTitle",
    subtitleKey: "onboarding.feedTourSubtitle",
    features: [
      {
        icon: "newspaper.fill",
        color: "#8b5cf6",
        bgColor: "#ede9fe",
        titleKey: "onboarding.feedTourActivity",
        detailKey: "onboarding.feedTourActivityDetail",
      },
      {
        icon: "heart.fill",
        color: "#ef4444",
        bgColor: "#fee2e2",
        titleKey: "onboarding.feedTourInteract",
        detailKey: "onboarding.feedTourInteractDetail",
      },
      {
        icon: "mic.fill",
        color: "#3b82f6",
        bgColor: "#dbeafe",
        titleKey: "onboarding.feedTourContribute",
        detailKey: "onboarding.feedTourContributeDetail",
      },
    ],
  },
  profile: {
    route: "/(tabs)/profile",
    audience: "all",
    heroIcon: "person.fill",
    heroColor: "#10b981",
    heroBg: "#d1fae5",
    titleKey: "onboarding.profileTourTitle",
    subtitleKey: "onboarding.profileTourSubtitle",
    features: [
      {
        icon: "flame.fill",
        color: "#f59e0b",
        bgColor: "#fef3c7",
        titleKey: "onboarding.profileTourStats",
        detailKey: "onboarding.profileTourStatsDetail",
      },
      {
        icon: "chart.bar.fill",
        color: "#3b82f6",
        bgColor: "#dbeafe",
        titleKey: "onboarding.profileTourDashboard",
        detailKey: "onboarding.profileTourDashboardDetail",
      },
      {
        icon: "person.3.fill",
        color: "#10b981",
        bgColor: "#d1fae5",
        titleKey: "onboarding.profileTourClassroom",
        detailKey: "onboarding.profileTourClassroomDetail",
      },
      {
        icon: "star.fill",
        color: "#f59e0b",
        bgColor: "#fef3c7",
        titleKey: "onboarding.profileTourBounties",
        detailKey: "onboarding.profileTourBountiesDetail",
      },
    ],
  },
  dashboard: {
    route: "/dashboard",
    audience: "all",
    heroIcon: "chart.bar.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Progress Dashboard",
    subtitle: "Track your trends and consistency.",
    features: [defaultFeature("Use this screen to monitor streak health, lesson completion, and XP momentum.")],
  },
  settings: {
    route: "/settings",
    audience: "all",
    heroIcon: "gearshape.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Settings",
    subtitle: "Customize your experience.",
    features: [defaultFeature("Manage app behavior, account preferences, and notification defaults here.")],
  },
  notifications: {
    route: "/notifications",
    audience: "all",
    heroIcon: "bell.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Notifications",
    subtitle: "Stay informed without missing key updates.",
    features: [defaultFeature("Review your alerts, activity updates, and actionable reminders in one feed.")],
  },
  dictionary: {
    route: "/dictionary",
    audience: "all",
    heroIcon: "character.book.closed",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Dictionary",
    subtitle: "Search and explore vocabulary.",
    features: [defaultFeature("Find words quickly, listen to pronunciations, and save terms for review.")],
  },
  quiz: {
    route: "/quiz",
    audience: "all",
    heroIcon: "trophy.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Quiz",
    subtitle: "Test recall and comprehension.",
    features: [defaultFeature("Choose a quiz length, answer quickly, and use results to target weak areas.")],
  },
  wordReview: {
    route: "/word-review",
    audience: "all",
    heroIcon: "brain.head.profile",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Word Review",
    subtitle: "Reinforce memory with spaced repetition.",
    features: [defaultFeature("Complete review sessions regularly to improve long-term retention.")],
  },
  matchingGame: {
    route: "/matching-game",
    audience: "all",
    heroIcon: "rectangle.grid.2x2",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Matching Game",
    subtitle: "Build speed and recognition.",
    features: [defaultFeature("Pair words with meanings under time pressure to strengthen quick recall.")],
  },
  geezLesson: {
    route: "/geez-lesson",
    audience: "all",
    heroIcon: "textformat.abc",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Ge'ez Practice",
    subtitle: "Learn script fundamentals.",
    features: [defaultFeature("Practice character recognition and writing flow for Ethiopic script.")],
  },
  adinkra: {
    route: "/adinkra",
    audience: "all",
    heroIcon: "sparkles.square.filled.on.square",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Adinkra Symbols",
    subtitle: "Explore cultural symbols and meanings.",
    features: [defaultFeature("Discover symbolism and context connected to language and heritage.")],
  },
  contributors: {
    route: "/contributors",
    audience: "all",
    heroIcon: "person.3.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Contributors",
    subtitle: "See who is growing the language data.",
    features: [defaultFeature("Use the leaderboard to discover active contributors and community leaders.")],
  },
  bounties: {
    route: "/bounties",
    audience: "all",
    heroIcon: "star.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Bounties",
    subtitle: "Earn rewards for high-value contributions.",
    features: [defaultFeature("Complete bounty tasks to unlock bonus XP and support content expansion.")],
  },
  bountyCreate: {
    route: "/bounty-create",
    audience: "admin",
    heroIcon: "star.circle.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Create Bounty",
    subtitle: "Define targeted contribution tasks.",
    features: [defaultFeature("Set clear bounty requirements, scope, and reward amounts before publishing.")],
  },
  contribute: {
    route: "/contribute",
    audience: "contributor",
    heroIcon: "mic.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Contribute",
    subtitle: "Submit words and recordings.",
    features: [defaultFeature("Provide high-quality terms, metadata, and pronunciation samples.")],
  },
  contributeLesson: {
    route: "/contribute-lesson",
    audience: "contributor",
    heroIcon: "book.pages.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Contribute Lesson",
    subtitle: "Build lesson-level content.",
    features: [defaultFeature("Structure lesson content with segments and supporting media.")],
  },
  contributeBulk: {
    route: "/contribute-bulk",
    audience: "contributor",
    heroIcon: "square.stack.3d.up.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Bulk Contribution",
    subtitle: "Upload multiple entries faster.",
    features: [defaultFeature("Use bulk mode for high-volume vocabulary imports with consistent formatting.")],
  },
  myContributions: {
    route: "/my-contributions",
    audience: "contributor",
    heroIcon: "doc.text.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "My Contributions",
    subtitle: "Track submission progress.",
    features: [defaultFeature("Review pending, approved, and rejected submissions and iterate quickly.")],
  },
  review: {
    route: "/review",
    audience: "reviewer",
    heroIcon: "checkmark.shield.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Review Queue",
    subtitle: "Moderate incoming contributions.",
    features: [defaultFeature("Validate quality, enforce standards, and provide actionable reviewer feedback.")],
  },
  reviewerApplication: {
    route: "/reviewer-application",
    audience: "all",
    heroIcon: "person.badge.plus",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Reviewer Application",
    subtitle: "Apply for advanced moderation roles.",
    features: [defaultFeature("Submit your experience to request reviewer permissions.")],
  },
  classroomHome: {
    route: "/classroom",
    audience: "all",
    heroIcon: "person.3.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Classroom",
    subtitle: "Collaborate in group learning spaces.",
    features: [defaultFeature("Join or manage classes and keep assignment progress organized.")],
  },
  classroomCreate: {
    route: "/classroom/create",
    audience: "all",
    heroIcon: "plus.rectangle.on.folder.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Create or Join Classroom",
    subtitle: "Set up your learning group.",
    features: [defaultFeature("Create new groups or join existing ones with invite details.")],
  },
  classroomGroup: {
    route: "/classroom/[groupId]",
    audience: "all",
    heroIcon: "person.2.square.stack.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Classroom Group",
    subtitle: "Manage members and progress.",
    features: [defaultFeature("Use this screen to coordinate lessons, members, and outcomes.")],
  },
  classroomAssign: {
    route: "/classroom/[groupId]/assign",
    audience: "all",
    heroIcon: "checklist",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Assign Lessons",
    subtitle: "Distribute learning tasks clearly.",
    features: [defaultFeature("Select lessons and assign due expectations for your class.")],
  },
  multiplayerHome: {
    route: "/multiplayer",
    audience: "all",
    heroIcon: "gamecontroller.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Multiplayer",
    subtitle: "Compete and learn with others.",
    features: [defaultFeature("Choose a mode and start real-time sessions with peers.")],
  },
  multiplayerLobby: {
    route: "/multiplayer/lobby",
    audience: "all",
    heroIcon: "person.2.wave.2.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Multiplayer Lobby",
    subtitle: "Match with another learner.",
    features: [defaultFeature("Create or join sessions and confirm readiness before starting.")],
  },
  multiplayerPairedLesson: {
    route: "/multiplayer/paired-lesson",
    audience: "all",
    heroIcon: "book.closed.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Paired Lesson",
    subtitle: "Synchronize lesson progress together.",
    features: [defaultFeature("Stay in sync with your partner while progressing through shared content.")],
  },
  multiplayerQuizBattle: {
    route: "/multiplayer/quiz-battle",
    audience: "all",
    heroIcon: "bolt.circle.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Quiz Battle",
    subtitle: "Compete in timed question rounds.",
    features: [defaultFeature("Answer quickly and accurately to beat your opponent.")],
  },
  multiplayerPairedResults: {
    route: "/multiplayer/paired-results",
    audience: "all",
    heroIcon: "flag.checkered.circle.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Paired Results",
    subtitle: "Review shared session outcomes.",
    features: [defaultFeature("Use result insights to pick the next lesson focus.")],
  },
  multiplayerQuizResults: {
    route: "/multiplayer/quiz-results",
    audience: "all",
    heroIcon: "trophy.circle.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Battle Results",
    subtitle: "Analyze performance and rematch.",
    features: [defaultFeature("Review question accuracy and launch a rematch quickly.")],
  },
  lessonDetail: {
    route: "/lesson/[id]",
    audience: "all",
    heroIcon: "book.pages.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Lesson Detail",
    subtitle: "Learn with audio and transcript support.",
    features: [defaultFeature("Play, pause, and follow content step-by-step before marking complete.")],
  },
  wordDetail: {
    route: "/word/[id]",
    audience: "all",
    heroIcon: "text.book.closed.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Word Detail",
    subtitle: "Inspect a word deeply.",
    features: [defaultFeature("Review pronunciation, meaning, and usage context for each term.")],
  },
  storyDetail: {
    route: "/story/[courseId]",
    audience: "all",
    heroIcon: "book.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Story Mode",
    subtitle: "Practice with narrative context.",
    features: [defaultFeature("Progress through stories to improve comprehension and retention.")],
  },
  culturalDetail: {
    route: "/cultural/[languageId]",
    audience: "all",
    heroIcon: "globe.americas.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Cultural Content",
    subtitle: "Learn through culture and history.",
    features: [defaultFeature("Connect vocabulary to stories, traditions, and real-world context.")],
  },
  proverbsDetail: {
    route: "/proverbs/[languageId]",
    audience: "all",
    heroIcon: "quote.bubble.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Proverbs",
    subtitle: "Study wisdom expressions by language.",
    features: [defaultFeature("Explore proverb meaning and usage to deepen fluency.")],
  },
  signIn: {
    route: "/(auth)/sign-in",
    audience: "all",
    heroIcon: "person.crop.circle.badge.checkmark",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Sign In",
    subtitle: "Access your learning account.",
    features: [defaultFeature("Sign in to sync progress and unlock community features.")],
  },
  signUp: {
    route: "/(auth)/sign-up",
    audience: "all",
    heroIcon: "person.crop.circle.badge.plus",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Create Account",
    subtitle: "Set up your learner profile.",
    features: [defaultFeature("Register to save progress, join classes, and contribute content.")],
  },
  verifyEmail: {
    route: "/(auth)/verify-email",
    audience: "all",
    heroIcon: "envelope.badge.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Verify Email",
    subtitle: "Secure your account setup.",
    features: [defaultFeature("Enter your code to complete authentication and continue.")],
  },
  onboarding: {
    route: "/(onboarding)",
    audience: "all",
    heroIcon: "sparkles",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Onboarding",
    subtitle: "Personalize your starting experience.",
    features: [defaultFeature("Pick your language and goals so the app can tailor learning paths.")],
  },
  restoreAccount: {
    route: "/restore-account",
    audience: "all",
    heroIcon: "arrow.uturn.backward.circle.fill",
    heroColor: "#2563eb",
    heroBg: "#dbeafe",
    title: "Restore Account",
    subtitle: "Recover account access safely.",
    features: [defaultFeature("Use this recovery flow to restore recently deleted accounts.")],
  },
} as const;

export type TourId = keyof typeof MOBILE_TOUR_REGISTRY;