import { Providers } from "@/components/providers";
import { THEME_INIT_SCRIPT } from "@/lib/theme";
import {
  normalizeUiLanguage,
  UI_LANGUAGE_COOKIE,
  type UiLanguage,
} from "@/lib/ui-language";
import { en } from "@mobile/lib/locales/en";
import { fr } from "@mobile/lib/locales/fr";
import { pcm } from "@mobile/lib/locales/pcm";
import type { Metadata } from "next";
import { Cormorant_Garamond, IBM_Plex_Mono, Plus_Jakarta_Sans } from "next/font/google";
import { cookies } from "next/headers";
import Script from "next/script";
import "./globals.css";

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://izon-beeli.com";
const APP_NAME = "Beeli (Aurufie)";
const APP_SECOND_NAME = "Aurufie";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
  display: "swap",
});

const ibmMono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: ["400", "500"],
  display: "swap",
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-display",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const TRANSLATIONS = { en, fr, pcm } as const;

async function getUiLanguage(): Promise<UiLanguage> {
  const cookieStore = await cookies();
  return normalizeUiLanguage(cookieStore.get(UI_LANGUAGE_COOKIE)?.value);
}

export async function generateMetadata(): Promise<Metadata> {
  const lang = await getUiLanguage();
  const copy = TRANSLATIONS[lang].web;
  const metadataBase = new URL(BASE_URL);

  return {
    metadataBase,
    title: {
      default: copy.metadataTitle,
      template: `%s | ${APP_NAME}`,
    },
    description: copy.metadataDescription,
    applicationName: APP_NAME,
    alternates: {
      canonical: "/",
    },
    category: "education",
    keywords: [
      "Beeli",
      "Aurufie",
      "African language learning",
      "Izon learning app",
      "learn Izon",
      "Niger Delta language",
      "language app",
    ],
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
    icons: {
      icon: "/favicon.svg",
    },
    openGraph: {
      title: copy.metadataTitle,
      description: copy.metadataDescription,
      url: metadataBase,
      siteName: APP_NAME,
      type: "website",
      locale: lang === "fr" ? "fr_FR" : "en_US",
      images: [
        {
          // Generated by app/opengraph-image.tsx (1200×630)
          url: "/opengraph-image",
          width: 1200,
          height: 630,
          alt: `${APP_NAME} — African Language Learning`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: copy.metadataTitle,
      description: copy.metadataDescription,
      images: ["/opengraph-image"],
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = await getUiLanguage();
  const organizationJsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: APP_NAME,
    alternateName: APP_SECOND_NAME,
    url: BASE_URL,
    logo: `${BASE_URL}/favicon.svg`,
    sameAs: [],
  };
  const websiteJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: APP_NAME,
    alternateName: APP_SECOND_NAME,
    url: BASE_URL,
    inLanguage: ["en", "fr", "pcm"],
  };
  const softwareAppJsonLd = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: APP_NAME,
    alternateName: APP_SECOND_NAME,
    url: BASE_URL,
    applicationCategory: "EducationApplication",
    operatingSystem: "iOS, Android, Web",
    inLanguage: ["en", "fr", "pcm"],
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
    description:
      "Beeli (Aurufie) is an African language learning platform focusing on Izon and other Niger Delta languages.",
  };

  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={`${jakarta.variable} ${cormorant.variable} ${ibmMono.variable} font-sans`}>
        <Script id="ld-org" type="application/ld+json" strategy="beforeInteractive">
          {JSON.stringify(organizationJsonLd)}
        </Script>
        <Script id="ld-website" type="application/ld+json" strategy="beforeInteractive">
          {JSON.stringify(websiteJsonLd)}
        </Script>
        <Script id="ld-app" type="application/ld+json" strategy="beforeInteractive">
          {JSON.stringify(softwareAppJsonLd)}
        </Script>
        <Script id="theme-init" strategy="beforeInteractive">
          {THEME_INIT_SCRIPT}
        </Script>
        <Providers initialUiLanguage={lang}>{children}</Providers>
      </body>
    </html>
  );
}
