import type { Course, Lesson, TranscriptSegment, JournalEntry, FeedItem, Comment, Language } from "@/types";

// Local Izon audio recordings
const AUDIO_IZON_BAI = require("../public/izon_bai.m4a");
const AUDIO_IZON_BO = require("../public/izon_bo.m4a");
const AUDIO_IZON_DOO = require("../public/izon_doo.m4a");
const AUDIO_IZON_MU = require("../public/izon_mu.m4a");
const AUDIO_IZON_NUA = require("../public/izon_nua.m4a");

// Sound effects
export const SFX_CORRECT = require("../public/correct.mp3");
export const SFX_INCORRECT = require("../public/incorrect.mp3");
export const SFX_FINISH = require("../public/finish.wav");

export const LANGUAGES: Language[] = [
  // Niger Delta
  { id: "izon", name: "Izon (Ijaw)", nativeName: "Ịzọn", region: "Niger Delta" },
  { id: "isoko", name: "Isoko", nativeName: "Isoko", region: "Niger Delta" },
  { id: "urhobo", name: "Urhobo", nativeName: "Urhobo", region: "Niger Delta" },
  { id: "itsekiri", name: "Itsekiri", nativeName: "Itsekiri", region: "Niger Delta" },
  { id: "ogbia", name: "Ogbia", nativeName: "Ogbia", region: "Niger Delta" },
  { id: "nembe", name: "Nembe", nativeName: "Nembe", region: "Niger Delta" },
  { id: "epie", name: "Epie-Atissa", nativeName: "Epie", region: "Niger Delta" },
  // Southwest
  { id: "yoruba", name: "Yoruba", nativeName: "Yorùbá", region: "Southwest" },
  { id: "igala", name: "Igala", nativeName: "Igala", region: "Southwest" },
  { id: "edo", name: "Edo (Bini)", nativeName: "Ẹdo", region: "Southwest" },
  { id: "esan", name: "Esan", nativeName: "Esan", region: "Southwest" },
  { id: "etsako", name: "Etsako", nativeName: "Etsako", region: "Southwest" },
  // Southeast
  { id: "igbo", name: "Igbo", nativeName: "Igbo", region: "Southeast" },
  { id: "ibibio", name: "Ibibio", nativeName: "Ibibio", region: "Southeast" },
  { id: "efik", name: "Efik", nativeName: "Efịk", region: "Southeast" },
  { id: "annang", name: "Annang", nativeName: "Annang", region: "Southeast" },
  { id: "ekene", name: "Ikwerre", nativeName: "Ikwerre", region: "Southeast" },
  { id: "ogoni", name: "Ogoni (Khana)", nativeName: "Khana", region: "Southeast" },
  // North Central
  { id: "tiv", name: "Tiv", nativeName: "Tiv", region: "North Central" },
  { id: "nupe", name: "Nupe", nativeName: "Nupe", region: "North Central" },
  { id: "gbagyi", name: "Gbagyi", nativeName: "Gbagyi", region: "North Central" },
  { id: "idoma", name: "Idoma", nativeName: "Idoma", region: "North Central" },
  { id: "jukun", name: "Jukun", nativeName: "Jukun", region: "North Central" },
  { id: "berom", name: "Berom", nativeName: "Berom", region: "North Central" },
  // North
  { id: "hausa", name: "Hausa", nativeName: "Hausa", region: "North" },
  { id: "kanuri", name: "Kanuri", nativeName: "Kanuri", region: "North" },
  { id: "fulfulde", name: "Fulfulde (Fula)", nativeName: "Fulfulde", region: "North" },
  { id: "margi", name: "Margi", nativeName: "Margi", region: "North" },
  { id: "bura", name: "Bura", nativeName: "Bura", region: "North" },
  // West Africa (non-Nigeria)
  { id: "akan", name: "Akan (Twi)", nativeName: "Akan", region: "West Africa" },
  { id: "ga", name: "Ga", nativeName: "Ga", region: "West Africa" },
  { id: "ewe", name: "Ewe", nativeName: "Eʋegbe", region: "West Africa" },
  { id: "wolof", name: "Wolof", nativeName: "Wolof", region: "West Africa" },
  { id: "bambara", name: "Bambara", nativeName: "Bamanankan", region: "West Africa" },
  { id: "mandinka", name: "Mandinka", nativeName: "Mandinka", region: "West Africa" },
  { id: "fon", name: "Fon", nativeName: "Fɔ̀ngbè", region: "West Africa" },
  { id: "mende", name: "Mende", nativeName: "Mɛnde", region: "West Africa" },
  { id: "krio", name: "Krio", nativeName: "Krio", region: "West Africa" },
  { id: "temne", name: "Temne", nativeName: "Temne", region: "West Africa" },
  { id: "dagbani", name: "Dagbani", nativeName: "Dagbanli", region: "West Africa" },
  { id: "moore", name: "Mooré", nativeName: "Mòoré", region: "West Africa" },
  // East Africa
  { id: "swahili", name: "Swahili", nativeName: "Kiswahili", region: "East Africa" },
  { id: "amharic", name: "Amharic", nativeName: "አማርኛ", region: "East Africa" },
  { id: "oromo", name: "Oromo", nativeName: "Afaan Oromoo", region: "East Africa" },
  { id: "tigrinya", name: "Tigrinya", nativeName: "ትግርኛ", region: "East Africa" },
  { id: "somali", name: "Somali", nativeName: "Soomaali", region: "East Africa" },
  { id: "luganda", name: "Luganda", nativeName: "Luganda", region: "East Africa" },
  { id: "kinyarwanda", name: "Kinyarwanda", nativeName: "Ikinyarwanda", region: "East Africa" },
  { id: "kirundi", name: "Kirundi", nativeName: "Ikirundi", region: "East Africa" },
  { id: "kikuyu", name: "Kikuyu", nativeName: "Gĩkũyũ", region: "East Africa" },
  { id: "luo", name: "Luo", nativeName: "Dholuo", region: "East Africa" },
  { id: "maasai", name: "Maasai", nativeName: "ɔl Maa", region: "East Africa" },
  // North Africa
  { id: "arabic-egyptian", name: "Arabic (Egyptian)", nativeName: "العربية المصرية", region: "North Africa" },
  { id: "arabic-maghrebi", name: "Arabic (Maghrebi)", nativeName: "الدارجة", region: "North Africa" },
  { id: "tamazight", name: "Tamazight (Berber)", nativeName: "ⵜⴰⵎⴰⵣⵉⵖⵜ", region: "North Africa" },
  { id: "kabyle", name: "Kabyle", nativeName: "Taqbaylit", region: "North Africa" },
  { id: "tuareg", name: "Tuareg (Tamashek)", nativeName: "Tamasheq", region: "North Africa" },
  { id: "coptic", name: "Coptic", nativeName: "ϯⲙⲉⲧⲣⲉⲙⲛⲕⲏⲙⲓ", region: "North Africa" },
  // Southern Africa
  { id: "zulu", name: "Zulu", nativeName: "isiZulu", region: "Southern Africa" },
  { id: "xhosa", name: "Xhosa", nativeName: "isiXhosa", region: "Southern Africa" },
  { id: "sotho", name: "Sotho", nativeName: "Sesotho", region: "Southern Africa" },
  { id: "tswana", name: "Tswana", nativeName: "Setswana", region: "Southern Africa" },
  { id: "shona", name: "Shona", nativeName: "chiShona", region: "Southern Africa" },
  { id: "ndebele", name: "Ndebele", nativeName: "isiNdebele", region: "Southern Africa" },
  { id: "tsonga", name: "Tsonga", nativeName: "Xitsonga", region: "Southern Africa" },
  { id: "venda", name: "Venda", nativeName: "Tshivenḓa", region: "Southern Africa" },
  { id: "swati", name: "Swati", nativeName: "siSwati", region: "Southern Africa" },
  { id: "afrikaans", name: "Afrikaans", nativeName: "Afrikaans", region: "Southern Africa" },
  { id: "chichewa", name: "Chichewa", nativeName: "Chicheŵa", region: "Southern Africa" },
  { id: "malagasy", name: "Malagasy", nativeName: "Malagasy", region: "Southern Africa" },
];

export const COURSES: Course[] = [
  // Izon
  {
    id: "course-1",
    title: "Izon Basics",
    description: "Learn the fundamentals of Izon language — greetings, introductions, and everyday phrases.",
    language: "izon",
    level: "beginner",
    lessonsCount: 5,
    progress: 40,
  },
  {
    id: "course-2",
    title: "Izon Stories",
    description: "Listen to traditional Izon folktales and build your listening comprehension.",
    language: "izon",
    level: "intermediate",
    lessonsCount: 2,
    progress: 0,
  },
  {
    id: "course-3",
    title: "Conversational Izon",
    description: "Master everyday conversations — markets, family, community, and greetings.",
    language: "izon",
    level: "beginner",
    lessonsCount: 1,
    progress: 0,
  },
  // Yoruba
  {
    id: "course-4",
    title: "Yoruba Basics",
    description: "Start your Yoruba journey with essential greetings and phrases used daily.",
    language: "yoruba",
    level: "beginner",
    lessonsCount: 3,
    progress: 0,
  },
  {
    id: "course-5",
    title: "Yoruba Proverbs",
    description: "Explore Yoruba wisdom through traditional proverbs and their meanings.",
    language: "yoruba",
    level: "intermediate",
    lessonsCount: 2,
    progress: 0,
  },
  // Igbo
  {
    id: "course-6",
    title: "Igbo Basics",
    description: "Learn fundamental Igbo phrases, greetings, and introductions.",
    language: "igbo",
    level: "beginner",
    lessonsCount: 3,
    progress: 0,
  },
  // Hausa
  {
    id: "course-7",
    title: "Hausa Basics",
    description: "Get started with Hausa — the most widely spoken language in West Africa.",
    language: "hausa",
    level: "beginner",
    lessonsCount: 2,
    progress: 0,
  },
  // Swahili
  {
    id: "course-8",
    title: "Swahili Basics",
    description: "Learn the lingua franca of East Africa — greetings, introductions, and everyday phrases.",
    language: "swahili",
    level: "beginner",
    lessonsCount: 3,
    progress: 0,
  },
  {
    id: "course-9",
    title: "Swahili Proverbs",
    description: "Discover the wisdom of East African cultures through Swahili proverbs.",
    language: "swahili",
    level: "intermediate",
    lessonsCount: 2,
    progress: 0,
  },
  // Amharic
  {
    id: "course-10",
    title: "Amharic Basics",
    description: "Start your journey with Ethiopia's official language — from greetings to daily conversation.",
    language: "amharic",
    level: "beginner",
    lessonsCount: 3,
    progress: 0,
  },
  // Akan (Twi)
  {
    id: "course-11",
    title: "Akan (Twi) Basics",
    description: "Learn the most widely spoken language in Ghana — greetings, phrases, and culture.",
    language: "akan",
    level: "beginner",
    lessonsCount: 3,
    progress: 0,
  },
  // Wolof
  {
    id: "course-12",
    title: "Wolof Basics",
    description: "Learn the dominant language of Senegal — known for its warmth and hospitality.",
    language: "wolof",
    level: "beginner",
    lessonsCount: 2,
    progress: 0,
  },
  // Arabic (Egyptian)
  {
    id: "course-13",
    title: "Egyptian Arabic Basics",
    description: "Learn the most widely understood Arabic dialect across North Africa and the Middle East.",
    language: "arabic-egyptian",
    level: "beginner",
    lessonsCount: 3,
    progress: 0,
  },
  // Somali
  {
    id: "course-14",
    title: "Somali Basics",
    description: "Get started with Somali — a Cushitic language with a rich oral tradition.",
    language: "somali",
    level: "beginner",
    lessonsCount: 2,
    progress: 0,
  },
  // Bambara
  {
    id: "course-15",
    title: "Bambara Basics",
    description: "Learn the most widely spoken language of Mali and the wider Manding family.",
    language: "bambara",
    level: "beginner",
    lessonsCount: 2,
    progress: 0,
  },
  // Tamazight
  {
    id: "course-16",
    title: "Tamazight Basics",
    description: "Explore the ancient Berber language of North Africa — spoken across Morocco and Algeria.",
    language: "tamazight",
    level: "beginner",
    lessonsCount: 2,
    progress: 0,
  },
  // Kinyarwanda
  {
    id: "course-17",
    title: "Kinyarwanda Basics",
    description: "Learn the national language of Rwanda — one of the most widely spoken Bantu languages.",
    language: "kinyarwanda",
    level: "beginner",
    lessonsCount: 2,
    progress: 0,
  },
  // Ewe
  {
    id: "course-18",
    title: "Ewe Basics",
    description: "Learn Ewe, spoken in Ghana and Togo — a tonal language with beautiful musicality.",
    language: "ewe",
    level: "beginner",
    lessonsCount: 2,
    progress: 0,
  },
  // Izon — Sounds & Spelling
  {
    id: "course-19",
    title: "Izon Sounds & Spelling",
    description: "Master the phonetics of Izon — vowel harmony, consonant digraphs, nasalized vowels, and spelling rules.",
    language: "izon",
    level: "beginner",
    lessonsCount: 4,
    progress: 0,
  },
  // Izon — Numbers & Money
  {
    id: "course-20",
    title: "Izon Numbers & Money",
    description: "Learn the traditional Izon counting system and the akpa money system used in markets.",
    language: "izon",
    level: "beginner",
    lessonsCount: 3,
    progress: 0,
  },
];

// --- Story-based transcripts ---

// Izon: A stranger arrives in the village and must learn greetings
const TRANSCRIPT_LESSON_1: TranscriptSegment[] = [
  { id: "t1", startTime: 0, endTime: 3, text: "Kẹni kẹni, owei kẹnị bo ama kpo sẹi", translation: "Once upon a time, a stranger arrived in a village" },
  { id: "t2", startTime: 3, endTime: 6.5, text: "Pekei pekei ama sụọ mene, Baidẹ!", translation: "Early in the morning he entered the town: Good morning!" },
  { id: "t3", startTime: 6.5, endTime: 10, text: "Kosu dau kẹnị gba: Teki ina ẹrẹ?", translation: "An elder asked: What is your name?" },
  { id: "t4", startTime: 10, endTime: 14, text: "Ina ẹrẹmẹ Timi. Tụbara?", translation: "My name is Timi. How are you?" },
  { id: "t5", startTime: 14, endTime: 18, text: "Emi! Kuro nimi, the elder replied", translation: "I am fine! I am well, the elder replied" },
  { id: "t6", startTime: 18, endTime: 22, text: "Ụmbana, Timi said. Doo!", translation: "Thank you, Timi said. Thank you!" },
  { id: "t7", startTime: 22, endTime: 26, text: "Nụa! Ebodẹ-a! the village welcomed him", translation: "Welcome! Welcome! the village greeted him" },
  { id: "t8", startTime: 26, endTime: 30, text: "Baịyo, owei! Bunuda seri!", translation: "Good night, friend! Sleep well!" },
];

// Izon: The tortoise and the river — traditional folktale
const TRANSCRIPT_LESSON_2: TranscriptSegment[] = [
  { id: "t2-1", startTime: 0, endTime: 4, text: "Kẹni kẹni, ebifaa kpo amọ ba sẹi", translation: "Long ago, a tortoise lived in the forest" },
  { id: "t2-2", startTime: 4, endTime: 8, text: "Ebifaa naa bọrọ faa sẹi", translation: "The tortoise was very clever" },
  { id: "t2-3", startTime: 8, endTime: 12, text: "Ọ bẹlẹ naa ọgbọ kpo amọ sei", translation: "One day he saw a river" },
  { id: "t2-4", startTime: 12, endTime: 16, text: "Ọgbọ naa yeri bou faa sẹi", translation: "The river was very wide" },
  { id: "t2-5", startTime: 16, endTime: 20, text: "Ebifaa naa sẹi a dẹi?", translation: "What did the tortoise do?" },
  { id: "t2-6", startTime: 20, endTime: 24, text: "Ọ kiri fịn timi sẹi", translation: "He thought very carefully" },
];

// Yoruba: The trader's son learns greetings at the market
const TRANSCRIPT_YORUBA_1: TranscriptSegment[] = [
  { id: "ty1", startTime: 0, endTime: 3.5, text: "Ọmọ ọja kan jí ni kutukutu owurọ", translation: "A trader's son woke up early one morning" },
  { id: "ty2", startTime: 3.5, endTime: 7, text: "E kaaro o! ó kí iya rẹ", translation: "Good morning! he greeted his mother" },
  { id: "ty3", startTime: 7, endTime: 11, text: "Bawo ni, ọmọ mi? iya rẹ bi", translation: "How are you, my child? his mother asked" },
  { id: "ty4", startTime: 11, endTime: 15, text: "Mo wa daadaa. Mo fẹ lọ si ọja", translation: "I am fine. I want to go to the market" },
  { id: "ty5", startTime: 15, endTime: 19, text: "Oruko mi ni Adé, ó sọ fun alajapa kan", translation: "My name is Adé, he told a stranger" },
  { id: "ty6", startTime: 19, endTime: 23, text: "Nibo lo n lo? alajapa naa bi", translation: "Where are you going? the stranger asked" },
  { id: "ty7", startTime: 23, endTime: 27, text: "Mo n lo si ọja. E se pupo!", translation: "I am going to the market. Thank you very much!" },
  { id: "ty8", startTime: 27, endTime: 30, text: "O dabo! Adé yọ si ọja", translation: "Goodbye! Adé smiled as he reached the market" },
];

// Igbo: The storyteller's grandchild visits during the new yam festival
const TRANSCRIPT_IGBO_1: TranscriptSegment[] = [
  { id: "ti1", startTime: 0, endTime: 3.5, text: "Ututu oma! Nne nne ya kpọrọ ya", translation: "Good morning! His grandmother called him" },
  { id: "ti2", startTime: 3.5, endTime: 7, text: "Aha m bu Chidi, ọ zara", translation: "My name is Chidi, he answered" },
  { id: "ti3", startTime: 7, endTime: 11, text: "Kedu ka i mere? Nne nne ya jụrụ", translation: "How are you? his grandmother asked" },
  { id: "ti4", startTime: 11, endTime: 15, text: "A di m mma! Taa bụ ụbọchị Iri Ji", translation: "I am fine! Today is the New Yam Festival" },
  { id: "ti5", startTime: 15, endTime: 19, text: "Dalu rinne, nne nne, maka nri a", translation: "Thank you very much, grandmother, for this food" },
  { id: "ti6", startTime: 19, endTime: 23, text: "Ebee ka i na aga? Nne nne ya jụrụ", translation: "Where are you going? his grandmother asked" },
  { id: "ti7", startTime: 23, endTime: 27, text: "Ana m aga n'ama — ebe ọgbakọ", translation: "I am going to the square — where the gathering is" },
  { id: "ti8", startTime: 27, endTime: 30, text: "Ka omesia! Jee nke oma!", translation: "See you later! Go well!" },
];

// Swahili: A dhow captain's first day on the coast
const TRANSCRIPT_SWAHILI_1: TranscriptSegment[] = [
  { id: "ts1", startTime: 0, endTime: 3, text: "Habari za asubuhi! nahodha alisema", translation: "Good morning! the captain said" },
  { id: "ts2", startTime: 3, endTime: 6.5, text: "Jina langu ni Baraka, kutoka Zanzibar", translation: "My name is Baraka, from Zanzibar" },
  { id: "ts3", startTime: 6.5, endTime: 10, text: "Habari yako? mvuvi alimwuliza", translation: "How are you? a fisherman asked him" },
  { id: "ts4", startTime: 10, endTime: 14, text: "Nzuri sana! Bahari ni shwari leo", translation: "Very well! The sea is calm today" },
  { id: "ts5", startTime: 14, endTime: 18, text: "Asante sana kwa ukarimu wako", translation: "Thank you very much for your hospitality" },
  { id: "ts6", startTime: 18, endTime: 22, text: "Unakwenda wapi na jahazi yako?", translation: "Where are you going with your dhow?" },
  { id: "ts7", startTime: 22, endTime: 26, text: "Ninakwenda Lamu, kisha nyumbani", translation: "I am going to Lamu, then home" },
  { id: "ts8", startTime: 26, endTime: 30, text: "Kwaheri! Safari njema!", translation: "Goodbye! Safe journey!" },
];

// Amharic: A coffee ceremony brings neighbors together
const TRANSCRIPT_AMHARIC_1: TranscriptSegment[] = [
  { id: "ta1", startTime: 0, endTime: 3, text: "እንደምን አደርክ! ጎረቤት ጠራ", translation: "Good morning! a neighbor called out" },
  { id: "ta2", startTime: 3, endTime: 6.5, text: "ስሜ ማርያም ነው። ቡና ፈልተሽ?", translation: "My name is Maryam. Would you like coffee?" },
  { id: "ta3", startTime: 6.5, endTime: 10, text: "እንዴት ነህ? ጎረቤት ጠየቀ", translation: "How are you? the neighbor asked" },
  { id: "ta4", startTime: 10, endTime: 14, text: "ደህና ነኝ! ቡና ሲፈላ ጥሩ ሽታ አለው", translation: "I am fine! The coffee smells wonderful as it brews" },
  { id: "ta5", startTime: 14, endTime: 18, text: "አመሰግናለሁ! ይህ የቡና ሥርዓት ቆንጆ ነው", translation: "Thank you! This coffee ceremony is beautiful" },
  { id: "ta6", startTime: 18, endTime: 22, text: "ወዴት ነው የምትሄደው? ከቡና በኋላ?", translation: "Where are you going after coffee?" },
  { id: "ta7", startTime: 22, endTime: 26, text: "ወደ ገበያ እየሄድኩ ነው — ቅመማ ቅመም ለመግዛት", translation: "I am going to the market — to buy spices" },
  { id: "ta8", startTime: 26, endTime: 30, text: "ደህና ሁን! ቡና ደግሞ ጠብቂኝ!", translation: "Goodbye! Save me coffee again!" },
];

// Akan: Ananse the spider visits his grandmother
const TRANSCRIPT_AKAN_1: TranscriptSegment[] = [
  { id: "tk1", startTime: 0, endTime: 3, text: "Maakye, Nana! Ananse kae", translation: "Good morning, Grandmother! Ananse said" },
  { id: "tk2", startTime: 3, endTime: 6.5, text: "Me din de Ananse, kwaku ananse", translation: "My name is Ananse, the clever spider" },
  { id: "tk3", startTime: 6.5, endTime: 10, text: "Wo ho te sɛn? Nana bisaa", translation: "How are you? Grandmother asked" },
  { id: "tk4", startTime: 10, endTime: 14, text: "Me ho yɛ! Nanso ɔkɔm de me", translation: "I am fine! But I am hungry" },
  { id: "tk5", startTime: 14, endTime: 18, text: "Medaase paa, Nana, sɛ wode aduane maa me", translation: "Thank you very much, Grandmother, for giving me food" },
  { id: "tk6", startTime: 18, endTime: 22, text: "Wo rekɔ he? Nana bisaa no", translation: "Where are you going? Grandmother asked him" },
  { id: "tk7", startTime: 22, endTime: 26, text: "Merekɔ fie, na ade resa", translation: "I am going home, it is getting dark" },
  { id: "tk8", startTime: 26, endTime: 30, text: "Nante yie, Ananse! Nana kae", translation: "Safe journey, Ananse! Grandmother said" },
];

// Wolof: A griot welcomes guests to a teranga feast
const TRANSCRIPT_WOLOF_1: TranscriptSegment[] = [
  { id: "tw1", startTime: 0, endTime: 3.5, text: "Nanga def? Gewel bi ne", translation: "How are you? the griot said" },
  { id: "tw2", startTime: 3.5, endTime: 7, text: "Maa ngi fi rekk. Teranga la", translation: "I am fine. This is hospitality" },
  { id: "tw3", startTime: 7, endTime: 11, text: "Naka nga tudd? Li ci nekkoon bi", translation: "What is your name? the host asked" },
  { id: "tw4", startTime: 11, endTime: 15, text: "Maa ngi tudd Ousmane. Sama kër Dakar la", translation: "My name is Ousmane. My home is Dakar" },
  { id: "tw5", startTime: 15, endTime: 19, text: "Jërëjëf ci teranga bi!", translation: "Thank you for this hospitality!" },
  { id: "tw6", startTime: 19, endTime: 23, text: "Fan nga dem? Gewel bi laaj", translation: "Where are you going? the griot asked" },
  { id: "tw7", startTime: 23, endTime: 27, text: "Damay dem kër, wànte dinaa dellu", translation: "I am going home, but I will return" },
  { id: "tw8", startTime: 27, endTime: 30, text: "Ba beneen, saai! the griot sang", translation: "See you again, friend! the griot sang" },
];

// Egyptian Arabic: A traveler discovers Cairo's old quarter
const TRANSCRIPT_ARABIC_EG_1: TranscriptSegment[] = [
  { id: "tae1", startTime: 0, endTime: 3, text: "صباح الخير! قال المسافر لصاحب القهوة", translation: "Good morning! the traveler said to the cafe owner" },
  { id: "tae2", startTime: 3, endTime: 6.5, text: "اسمي يوسف. أنا من الإسكندرية", translation: "My name is Youssef. I am from Alexandria" },
  { id: "tae3", startTime: 6.5, endTime: 10, text: "إزيك يا يوسف? صاحب القهوة سأل", translation: "How are you, Youssef? the cafe owner asked" },
  { id: "tae4", startTime: 10, endTime: 14, text: "أنا كويس! القاهرة جميلة", translation: "I am fine! Cairo is beautiful" },
  { id: "tae5", startTime: 14, endTime: 18, text: "شكراً جزيلاً على الشاي ده", translation: "Thank you very much for this tea" },
  { id: "tae6", startTime: 18, endTime: 22, text: "رايح فين دلوقتي? صاحب القهوة سأل", translation: "Where are you going now? the cafe owner asked" },
  { id: "tae7", startTime: 22, endTime: 26, text: "أنا رايح خان الخليلي — السوق القديم", translation: "I am going to Khan el-Khalili — the old market" },
  { id: "tae8", startTime: 26, endTime: 30, text: "مع السلامة! ارجع تاني!", translation: "Goodbye! Come back again!" },
];

export const LESSONS: Lesson[] = [
  // Izon course-1
  {
    id: "lesson-1",
    courseId: "course-1",
    title: "Greetings & Introductions",
    description: "Learn how to greet people and introduce yourself in Izon.",
    audioUrl: AUDIO_IZON_BAI,
    duration: 4,
    order: 1,
    completed: true,
    transcript: TRANSCRIPT_LESSON_1,
  },
  {
    id: "lesson-2",
    courseId: "course-1",
    title: "The Tortoise and the River",
    description: "A traditional Izon folktale about a clever tortoise.",
    audioUrl: AUDIO_IZON_NUA,
    duration: 5,
    order: 2,
    completed: true,
    transcript: TRANSCRIPT_LESSON_2,
  },
  {
    id: "lesson-3",
    courseId: "course-1",
    title: "Numbers & Counting",
    description: "Learn to count from 1 to 20 in Izon.",
    audioUrl: AUDIO_IZON_DOO,
    duration: 5,
    order: 3,
    completed: false,
  },
  {
    id: "lesson-4",
    courseId: "course-1",
    title: "Family Members",
    description: "Learn Izon words for family members and relationships.",
    audioUrl: AUDIO_IZON_MU,
    duration: 4,
    order: 4,
    completed: false,
  },
  {
    id: "lesson-5",
    courseId: "course-1",
    title: "Daily Activities",
    description: "Describe your daily routine using Izon verbs and phrases.",
    audioUrl: AUDIO_IZON_BO,
    duration: 5,
    order: 5,
    completed: false,
  },
  // Izon course-2: Stories — A grandfather tells his grandchild about Akasa and the Water Spirits
  {
    id: "lesson-6",
    courseId: "course-2",
    title: "The Akasa Forest",
    description: "A grandfather tells his grandchild about the sacred Akasa forest and the ancestors who dwell within.",
    audioUrl: AUDIO_IZON_NUA,
    duration: 5,
    order: 1,
    completed: false,
    transcript: [
      { id: "t6-1", startTime: 0, endTime: 3, text: "Kosu dada, Akasa ye denghi?", translation: "Grandpa, where is Akasa?" },
      { id: "t6-2", startTime: 3, endTime: 7, text: "Akasa ye bou tibi kpo. Tẹmẹ bou ye bei.", translation: "Akasa is deep in the forest. It is a spirit place." },
      { id: "t6-3", startTime: 7, endTime: 11, text: "Arị mu digha-a? Arị di mi!", translation: "Can I go there? I want to see it!" },
      { id: "t6-4", startTime: 11, endTime: 15, text: "Ọdudu ẹrẹ kịịrịị ye-a? Tẹmẹbọ bi mene.", translation: "Is your heart pure? The spirits will test you." },
      { id: "t6-5", startTime: 15, endTime: 19, text: "Tịn kẹnị seri mene bei kpo — Ịzọn tịn.", translation: "A great tree stands there — the Ijaw Tree." },
      { id: "t6-6", startTime: 19, endTime: 23, text: "Kosu daubọ bei kpo gba mene wuni kpo.", translation: "Our ancestors speak to us through that tree." },
      { id: "t6-7", startTime: 23, endTime: 27, text: "Arị dila! Arị bẹẹlị mi.", translation: "I understand! I want to learn more." },
      { id: "t6-8", startTime: 27, endTime: 31, text: "Doo, tubou ẹrẹ. Torụ angọ kụlụ bogha.", translation: "Good, my child. The river does not forget its source." },
    ],
  },
  {
    id: "lesson-7",
    courseId: "course-2",
    title: "The Water Spirit Festival",
    description: "A boy and his father prepare for the Owuamapu festival — learning about masks, colors, and dance.",
    audioUrl: AUDIO_IZON_DOO,
    duration: 5,
    order: 2,
    completed: false,
    transcript: [
      { id: "t7-1", startTime: 0, endTime: 3.5, text: "Dada, beingbai Owuamapu uge ye?", translation: "Dad, is today the Water Spirit festival?" },
      { id: "t7-2", startTime: 3.5, endTime: 7, text: "Heén! Bo, wuni mu.", translation: "Yes! Come, let us go." },
      { id: "t7-3", startTime: 7, endTime: 11, text: "Dada, ịndị anyẹn bei ye denghi kpọ?", translation: "Dad, why are they wearing fish masks?" },
      { id: "t7-4", startTime: 11, endTime: 15, text: "Owuamapu beni kpo timi. Ịndị ye woi leleị.", translation: "Water spirits live in the river. Fish are their sign." },
      { id: "t7-5", startTime: 15, endTime: 19, text: "Kwa-kwa aru bei — denghi kpọ kwa-kwa?", translation: "That red cloth — why is it red?" },
      { id: "t7-6", startTime: 19, endTime: 23, text: "Kwa-kwa ye gbasi. Pena-pena ye ọdudu kịịrịị.", translation: "Red means strength. White means a pure heart." },
      { id: "t7-7", startTime: 23, endTime: 27, text: "Dirimo-a? Dirimo ye dein mọ tẹmẹ.", translation: "And black? Black means night and spirits." },
      { id: "t7-8", startTime: 27, endTime: 31, text: "Arị sẹị mi! Arị Ịzọn ye!", translation: "I want to dance! I am Izon!" },
    ],
  },
  // Izon course-3: Conversational — Bargaining at the market
  {
    id: "lesson-8",
    courseId: "course-3",
    title: "At the Market",
    description: "Practice bargaining, asking prices, and making transactions at a busy Izon market.",
    audioUrl: AUDIO_IZON_MU,
    duration: 4,
    order: 1,
    completed: false,
    transcript: [
      { id: "t8-1", startTime: 0, endTime: 3.5, text: "Baidẹ! Yebị ẹndẹị buru bei?", translation: "Good morning! How much is this yam?" },
      { id: "t8-2", startTime: 3.5, endTime: 7, text: "Akpa mọ ekise mọ. Buru bei pere ye.", translation: "Three hundred naira. This yam is big." },
      { id: "t8-3", startTime: 7, endTime: 11, text: "Garịn! Tubobị Iyerimọ!", translation: "That's expensive! Make it cheaper!" },
      { id: "t8-4", startTime: 11, endTime: 14, text: "Akpa. Ma akpaa bogha.", translation: "Two hundred. Not four hundred." },
      { id: "t8-5", startTime: 14, endTime: 18, text: "Doo! Okubo kọọr yọ kei ipiri.", translation: "Thank you! Give me my change." },
      { id: "t8-6", startTime: 18, endTime: 22, text: "Ịndị bei-a? Yebị ẹndẹị?", translation: "And this fish? How much is it?" },
      { id: "t8-7", startTime: 22, endTime: 26, text: "Okubo faa! Deinbai arị bo mene.", translation: "I have no money left! I'll come tomorrow." },
      { id: "t8-8", startTime: 26, endTime: 30, text: "Ese faa! Deinbai bo. Ụmbana!", translation: "No problem! Come tomorrow. Thank you!" },
    ],
  },
  // Yoruba course-4: A trader's son navigates market life
  {
    id: "lesson-9",
    courseId: "course-4",
    title: "Adé Goes to Market",
    description: "Follow young Adé as he greets neighbors on his way to Oja Oba, the king's market.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    duration: 30,
    order: 1,
    completed: false,
    transcript: TRANSCRIPT_YORUBA_1,
  },
  {
    id: "lesson-10",
    courseId: "course-4",
    title: "Counting Cowries",
    description: "Adé's mother teaches him to count cowrie shells at her market stall.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    duration: 195,
    order: 2,
    completed: false,
    transcript: [
      { id: "ty10-1", startTime: 0, endTime: 0, text: "Adé, wa ka owó ẹyọ yìí", translation: "Adé, come count these cowrie shells" },
      { id: "ty10-2", startTime: 0, endTime: 0, text: "Okan, meji, mẹta, mẹrin, marun", translation: "One, two, three, four, five" },
      { id: "ty10-3", startTime: 0, endTime: 0, text: "Dáadáa! Mẹfa, meje, mẹjọ, mẹsan, mẹwa", translation: "Good! Six, seven, eight, nine, ten" },
      { id: "ty10-4", startTime: 0, endTime: 0, text: "Iye owó mẹwa ni ọja yìí?", translation: "This costs ten cowries at the market?" },
      { id: "ty10-5", startTime: 0, endTime: 0, text: "Bẹẹni! Mọkanla, mejila, mẹtala...", translation: "Yes! Eleven, twelve, thirteen..." },
      { id: "ty10-6", startTime: 0, endTime: 0, text: "Ìyá, mo ti mọ ogún! Mo le ka!", translation: "Mother, I know twenty now! I can count!" },
      { id: "ty10-7", startTime: 0, endTime: 0, text: "O ṣe daadaa, ọmọ mi. Ọja ti pe ọ.", translation: "Well done, my child. The market is calling you." },
    ],
  },
  {
    id: "lesson-11",
    courseId: "course-4",
    title: "Adé Meets the Family",
    description: "Adé introduces a new friend to his large Yoruba family at a naming ceremony.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    duration: 220,
    order: 3,
    completed: false,
    transcript: [
      { id: "ty11-1", startTime: 0, endTime: 0, text: "Ẹ wá, ẹ wá! Ọjọ ìsọmọlórúkọ ni o!", translation: "Come, come! It is a naming ceremony today!" },
      { id: "ty11-2", startTime: 0, endTime: 0, text: "Èyí ni bàbá mi. Father. Ẹ kú ọjọ!", translation: "This is my father. Father. Congratulations today!" },
      { id: "ty11-3", startTime: 0, endTime: 0, text: "Ìyá mi ni yìí. Mother. Ó ń ṣe oúnjẹ.", translation: "This is my mother. Mother. She is cooking." },
      { id: "ty11-4", startTime: 0, endTime: 0, text: "Ẹ̀gbọ́n mi Túndé. Àbúrò mi Kẹmi.", translation: "My older sibling Túndé. My younger sibling Kẹmi." },
      { id: "ty11-5", startTime: 0, endTime: 0, text: "Ìyá àgbà — grandmother. Bàbá àgbà — grandfather.", translation: "Grandmother. Grandfather." },
      { id: "ty11-6", startTime: 0, endTime: 0, text: "Àná mi ni yi — my in-law. E kú oríire!", translation: "This is my in-law. Congratulations!" },
      { id: "ty11-7", startTime: 0, endTime: 0, text: "Ẹbí ni agbára wa. Family is our strength.", translation: "Family is our strength." },
    ],
  },
  // Yoruba course-5: Proverbs told through conversation
  {
    id: "lesson-12",
    courseId: "course-5",
    title: "The Patient Farmer",
    description: "An elder teaches patience through Yoruba proverbs as a young farmer struggles with his harvest.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    duration: 260,
    order: 1,
    completed: false,
    transcript: [
      { id: "ty12-1", startTime: 0, endTime: 0, text: "Bàbá, oko mi kò dáa. Ohunkóhun kò hù!", translation: "Father, my farm is bad. Nothing is growing!" },
      { id: "ty12-2", startTime: 0, endTime: 0, text: "Ọmọ mi, sùúrù ni baba ìwà.", translation: "My child, patience is the father of good character." },
      { id: "ty12-3", startTime: 0, endTime: 0, text: "Àgbà kì í wà lọjà, kí orí ọmọ tuntun wọ́.", translation: "An elder is never absent from the market when a child's head is being shaped." },
      { id: "ty12-4", startTime: 0, endTime: 0, text: "Kí ni ìtumọ̀ rẹ̀?", translation: "What does that mean?" },
      { id: "ty12-5", startTime: 0, endTime: 0, text: "Ìgbà tí o bá nílò mi, emi yóò wà. Sùúrù.", translation: "When you need me, I will be there. Patience." },
      { id: "ty12-6", startTime: 0, endTime: 0, text: "Bí a kò bá gbàgbé ohun tí a ń gbìn, a á rí ohun tí a ó ka.", translation: "If we don't forget what we plant, we will have something to harvest." },
      { id: "ty12-7", startTime: 0, endTime: 0, text: "E ṣe pupo, bàbá. Mo ti lóye.", translation: "Thank you, father. I understand now." },
    ],
  },
  {
    id: "lesson-13",
    courseId: "course-5",
    title: "The Selfish Chief",
    description: "A village debates whether a chief who hoards grain deserves their loyalty — proverbs about community.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    duration: 240,
    order: 2,
    completed: false,
    transcript: [
      { id: "ty13-1", startTime: 0, endTime: 0, text: "Ọba wa kò fi oúnjẹ fún ènìyàn. Kí ni a ó ṣe?", translation: "Our chief does not share food with the people. What do we do?" },
      { id: "ty13-2", startTime: 0, endTime: 0, text: "Agbájọ ọwọ́ la fi ń sọ́ya. Àjọbi lẹ̀ṣẹ̀.", translation: "We wash our chest with joined hands. Kinship is like a foot." },
      { id: "ty13-3", startTime: 0, endTime: 0, text: "Ẹnì tí ó jẹ́ ẹnìkejì rẹ̀ ni yóò rí i gbé.", translation: "Only the one who feeds others will be carried by them." },
      { id: "ty13-4", startTime: 0, endTime: 0, text: "Ẹ jẹ́ á bá a sọ̀rọ̀. Àjùmọ̀ṣe ni agbára.", translation: "Let us speak with him. Unity is strength." },
      { id: "ty13-5", startTime: 0, endTime: 0, text: "Ọba, gbogbo wa ni ọja kan. A gbọ́dọ̀ pín.", translation: "Chief, we are all one market. We must share." },
      { id: "ty13-6", startTime: 0, endTime: 0, text: "Ẹ tọ́. Mo ti gbàgbé ohun tí ó ṣe pàtàkì jùlọ.", translation: "You are right. I forgot what matters most." },
    ],
  },
  // Igbo course-6: A grandchild visits during the Iri Ji festival
  {
    id: "lesson-14",
    courseId: "course-6",
    title: "Chidi's New Yam Festival",
    description: "Chidi arrives at his grandmother's village for Iri Ji — learning greetings along the way.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    duration: 30,
    order: 1,
    completed: false,
    transcript: TRANSCRIPT_IGBO_1,
  },
  {
    id: "lesson-15",
    courseId: "course-6",
    title: "Sharing the Harvest",
    description: "Chidi helps count and divide yams for the feast — learning numbers through the harvest.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    duration: 185,
    order: 2,
    completed: false,
    transcript: [
      { id: "ti15-1", startTime: 0, endTime: 0, text: "Chidi, bịa ka anyị gụọ ji a!", translation: "Chidi, come let us count these yams!" },
      { id: "ti15-2", startTime: 0, endTime: 0, text: "Otu, abụọ, atọ, anọ, ise", translation: "One, two, three, four, five" },
      { id: "ti15-3", startTime: 0, endTime: 0, text: "Isii, asaa, asatọ, itoolu, iri", translation: "Six, seven, eight, nine, ten" },
      { id: "ti15-4", startTime: 0, endTime: 0, text: "Nne nne, ji iri abụọ nke a zuru?", translation: "Grandmother, are twenty yams enough?" },
      { id: "ti15-5", startTime: 0, endTime: 0, text: "Iri na otu, iri na abụọ... iri abụọ!", translation: "Eleven, twelve... twenty!" },
      { id: "ti15-6", startTime: 0, endTime: 0, text: "Ọ zuru! Ugbu a kee anyị ha n'etiti ụmụnna.", translation: "It is enough! Now we divide them among the family." },
      { id: "ti15-7", startTime: 0, endTime: 0, text: "Igwe bụ ike — together we are strong!", translation: "Igwe bụ ike — the strength of numbers!" },
    ],
  },
  {
    id: "lesson-16",
    courseId: "course-6",
    title: "The Family Gathering",
    description: "Chidi introduces visitors to his extended family at the Iri Ji feast.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    duration: 210,
    order: 3,
    completed: false,
    transcript: [
      { id: "ti16-1", startTime: 0, endTime: 0, text: "Nne nne, onye bụ ndị a?", translation: "Grandmother, who are these people?" },
      { id: "ti16-2", startTime: 0, endTime: 0, text: "Nke a bụ nna m — your great-grandfather!", translation: "This is my father — your great-grandfather!" },
      { id: "ti16-3", startTime: 0, endTime: 0, text: "Nne m nọ ebe a. Nna m nọ ebe ahụ.", translation: "My mother is here. My father is over there." },
      { id: "ti16-4", startTime: 0, endTime: 0, text: "Nwanne m nwoke — brother. Nwanne m nwanyị — sister.", translation: "My brother. My sister." },
      { id: "ti16-5", startTime: 0, endTime: 0, text: "Ọgọ m — my in-law. Nwa nwa — grandchild.", translation: "My in-law. Grandchild." },
      { id: "ti16-6", startTime: 0, endTime: 0, text: "Ezinụlọ bụ ihe kachasị mkpa. Family is everything.", translation: "Family is the most important thing." },
    ],
  },
  // Hausa course-7: A traveling scholar arrives at the emir's court
  {
    id: "lesson-17",
    courseId: "course-7",
    title: "The Scholar's Arrival",
    description: "A young scholar arrives in Kano and must greet the emir's court with proper respect.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    duration: 175,
    order: 1,
    completed: false,
    transcript: [
      { id: "th17-1", startTime: 0, endTime: 0, text: "Ina kwana! Barka da zuwa Kano!", translation: "Good day! Welcome to Kano!" },
      { id: "th17-2", startTime: 0, endTime: 0, text: "Yaya dai? Sunana Musa ne.", translation: "How are you? My name is Musa." },
      { id: "th17-3", startTime: 0, endTime: 0, text: "Lafiya lau! Ina zuwa daga Zaria.", translation: "I am very well! I am coming from Zaria." },
      { id: "th17-4", startTime: 0, endTime: 0, text: "Me ka ke nema a nan?", translation: "What are you looking for here?" },
      { id: "th17-5", startTime: 0, endTime: 0, text: "Ina neman ilimi. Ina son in koyi.", translation: "I am seeking knowledge. I want to learn." },
      { id: "th17-6", startTime: 0, endTime: 0, text: "Madalla! Sarki zai karbe ka.", translation: "Wonderful! The emir will receive you." },
      { id: "th17-7", startTime: 0, endTime: 0, text: "Na gode sosai! Sai anjima!", translation: "Thank you very much! See you tomorrow!" },
    ],
  },
  {
    id: "lesson-18",
    courseId: "course-7",
    title: "Trading at Kurmi Market",
    description: "Musa learns to count and bargain at Kano's ancient Kurmi market.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    duration: 190,
    order: 2,
    completed: false,
    transcript: [
      { id: "th18-1", startTime: 0, endTime: 0, text: "Musa, ka zo kasuwa! Bari in koya maka.", translation: "Musa, come to the market! Let me teach you." },
      { id: "th18-2", startTime: 0, endTime: 0, text: "Ɗaya, biyu, uku, huɗu, biyar", translation: "One, two, three, four, five" },
      { id: "th18-3", startTime: 0, endTime: 0, text: "Shida, bakwai, takwas, tara, goma", translation: "Six, seven, eight, nine, ten" },
      { id: "th18-4", startTime: 0, endTime: 0, text: "Nawa ne wannan riga?", translation: "How much is this robe?" },
      { id: "th18-5", startTime: 0, endTime: 0, text: "Naira dubu ɗaya. — Yi mun rangwame!", translation: "One thousand naira. — Give me a discount!" },
      { id: "th18-6", startTime: 0, endTime: 0, text: "To, ɗari biyar. Ga canjin ka.", translation: "Okay, five hundred. Here is your change." },
      { id: "th18-7", startTime: 0, endTime: 0, text: "Na gode! Kasuwa ta Kurmi ba ta da iri!", translation: "Thank you! Kurmi market has no equal!" },
    ],
  },
  // Swahili course-8: A dhow captain's coastal journey
  {
    id: "lesson-19",
    courseId: "course-8",
    title: "Captain Baraka's Journey",
    description: "Follow Captain Baraka as he sails from Zanzibar and greets the fishermen of the coast.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    duration: 30,
    order: 1,
    completed: false,
    transcript: TRANSCRIPT_SWAHILI_1,
  },
  {
    id: "lesson-20",
    courseId: "course-8",
    title: "Counting the Catch",
    description: "Baraka helps fishermen count their catch and divide it for the village.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    duration: 200,
    order: 2,
    completed: false,
    transcript: [
      { id: "ts20-1", startTime: 0, endTime: 0, text: "Baraka, tuhesabu samaki! Moja, mbili, tatu...", translation: "Baraka, let's count the fish! One, two, three..." },
      { id: "ts20-2", startTime: 0, endTime: 0, text: "Nne, tano, sita, saba, nane", translation: "Four, five, six, seven, eight" },
      { id: "ts20-3", startTime: 0, endTime: 0, text: "Tisa, kumi! Samaki kumi leo!", translation: "Nine, ten! Ten fish today!" },
      { id: "ts20-4", startTime: 0, endTime: 0, text: "Kumi na moja, kumi na mbili... ishirini!", translation: "Eleven, twelve... twenty!" },
      { id: "ts20-5", startTime: 0, endTime: 0, text: "Tuigawanye. Kila nyumba ipate samaki.", translation: "Let's divide them. Every house should get fish." },
      { id: "ts20-6", startTime: 0, endTime: 0, text: "Umoja ni nguvu. Asante sana, Baraka!", translation: "Unity is strength. Thank you very much, Baraka!" },
    ],
  },
  {
    id: "lesson-21",
    courseId: "course-8",
    title: "The Fisherman's Family",
    description: "Baraka joins a fisherman's family for dinner and learns how they address each other.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    duration: 210,
    order: 3,
    completed: false,
    transcript: [
      { id: "ts21-1", startTime: 0, endTime: 0, text: "Karibu nyumbani kwangu! Njoo ukae na familia yangu.", translation: "Welcome to my home! Come sit with my family." },
      { id: "ts21-2", startTime: 0, endTime: 0, text: "Huyu ni baba yangu — mvuvi mkubwa.", translation: "This is my father — a great fisherman." },
      { id: "ts21-3", startTime: 0, endTime: 0, text: "Mama yangu anapika pilau. Bibi anamwambia siri.", translation: "My mother is cooking pilau. Grandmother is telling her secrets." },
      { id: "ts21-4", startTime: 0, endTime: 0, text: "Kaka yangu — brother. Dada yangu — sister.", translation: "My brother. My sister." },
      { id: "ts21-5", startTime: 0, endTime: 0, text: "Babu, tueleze hadithi ya zamani!", translation: "Grandfather, tell us an old story!" },
      { id: "ts21-6", startTime: 0, endTime: 0, text: "Familia ndio msingi wa maisha. Family is the foundation of life.", translation: "Family is the foundation of life." },
    ],
  },
  // Swahili course-9: Proverbs through conversation
  {
    id: "lesson-22",
    courseId: "course-9",
    title: "The Teacher and the Student",
    description: "A Swahili teacher shares proverbs about wisdom with a struggling student.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    duration: 250,
    order: 1,
    completed: false,
    transcript: [
      { id: "ts22-1", startTime: 0, endTime: 0, text: "Mwalimu, siwezi kuelewa! Ni vigumu sana.", translation: "Teacher, I cannot understand! It is very difficult." },
      { id: "ts22-2", startTime: 0, endTime: 0, text: "Haba na haba hujaza kibaba, mwanangu.", translation: "Little by little fills the container, my child." },
      { id: "ts22-3", startTime: 0, endTime: 0, text: "Maana yake ni nini?", translation: "What does that mean?" },
      { id: "ts22-4", startTime: 0, endTime: 0, text: "Jifunze kidogo kidogo. Usikate tamaa.", translation: "Learn bit by bit. Do not give up." },
      { id: "ts22-5", startTime: 0, endTime: 0, text: "Elimu ni bahari — haina mwisho.", translation: "Knowledge is an ocean — it has no end." },
      { id: "ts22-6", startTime: 0, endTime: 0, text: "Asante mwalimu! Nitajaribu tena kesho.", translation: "Thank you teacher! I will try again tomorrow." },
    ],
  },
  {
    id: "lesson-23",
    courseId: "course-9",
    title: "The Two Neighbors",
    description: "Two neighbors argue and reconcile — learning Swahili proverbs about unity.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    duration: 240,
    order: 2,
    completed: false,
    transcript: [
      { id: "ts23-1", startTime: 0, endTime: 0, text: "Jirani yangu, kwa nini huzungumzi nami?", translation: "My neighbor, why don't you speak to me?" },
      { id: "ts23-2", startTime: 0, endTime: 0, text: "Ulinichukia! Ulinisahau!", translation: "You wronged me! You forgot about me!" },
      { id: "ts23-3", startTime: 0, endTime: 0, text: "Kidole kimoja hakivunji chawa.", translation: "One finger cannot crush a louse." },
      { id: "ts23-4", startTime: 0, endTime: 0, text: "Tunahitajiana. Umoja ni nguvu, utengano ni udhaifu.", translation: "We need each other. Unity is strength, division is weakness." },
      { id: "ts23-5", startTime: 0, endTime: 0, text: "Uko sawa. Mtu ni watu — a person is people.", translation: "You are right. A person is people." },
      { id: "ts23-6", startTime: 0, endTime: 0, text: "Karibu nyumbani, rafiki yangu. Tuanze upya.", translation: "Welcome to my home, my friend. Let us start fresh." },
    ],
  },
  // Amharic course-10: The coffee ceremony and Ethiopian hospitality
  {
    id: "lesson-24",
    courseId: "course-10",
    title: "Maryam's Coffee Ceremony",
    description: "Maryam invites her neighbor for a traditional Ethiopian coffee ceremony — buna.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    duration: 30,
    order: 1,
    completed: false,
    transcript: TRANSCRIPT_AMHARIC_1,
  },
  {
    id: "lesson-25",
    courseId: "course-10",
    title: "The Spice Market",
    description: "Maryam bargains for spices at the merkato — learning to count in Amharic.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    duration: 195,
    order: 2,
    completed: false,
    transcript: [
      { id: "ta25-1", startTime: 0, endTime: 0, text: "ማርያም፣ ቅመማ ቅመም ስንት ትፈልጊ?", translation: "Maryam, how many spices do you want?" },
      { id: "ta25-2", startTime: 0, endTime: 0, text: "አንድ፣ ሁለት፣ ሶስት፣ አራት፣ አምስት", translation: "One, two, three, four, five" },
      { id: "ta25-3", startTime: 0, endTime: 0, text: "ስድስት፣ ሰባት፣ ስምንት፣ ዘጠኝ፣ አስር", translation: "Six, seven, eight, nine, ten" },
      { id: "ta25-4", startTime: 0, endTime: 0, text: "ይህ ስንት ነው? — ሃያ ብር", translation: "How much is this? — Twenty birr" },
      { id: "ta25-5", startTime: 0, endTime: 0, text: "ውድ ነው! አስር ብር? — እሺ፣ አስራ አምስት", translation: "That's expensive! Ten birr? — Okay, fifteen" },
      { id: "ta25-6", startTime: 0, endTime: 0, text: "አመሰግናለሁ! ቡና ላይ ይጣፍጣል!", translation: "Thank you! It will taste great in the coffee!" },
    ],
  },
  {
    id: "lesson-26",
    courseId: "course-10",
    title: "Gathering for Timkat",
    description: "Maryam's family gathers for the Timkat festival — introducing family members.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    duration: 205,
    order: 3,
    completed: false,
    transcript: [
      { id: "ta26-1", startTime: 0, endTime: 0, text: "ጤና ይስጥልኝ! ቲምከት ነው! ሁሉም ይምጣ!", translation: "Hello! It is Timkat! Let everyone come!" },
      { id: "ta26-2", startTime: 0, endTime: 0, text: "ይህ አባቴ ነው። ይህ እናቴ ናት።", translation: "This is my father. This is my mother." },
      { id: "ta26-3", startTime: 0, endTime: 0, text: "ወንድሜ ዳዊት — ታላቅ ወንድም።", translation: "My brother Dawit — big brother." },
      { id: "ta26-4", startTime: 0, endTime: 0, text: "እህቴ ሳራ — ትንሽ እህት ናት።", translation: "My sister Sara — she is the little sister." },
      { id: "ta26-5", startTime: 0, endTime: 0, text: "አያቴ — grandmother. አያቴ — grandfather.", translation: "Grandmother. Grandfather." },
      { id: "ta26-6", startTime: 0, endTime: 0, text: "ቤተሰብ ሁሉ ነገር ነው። Family is everything.", translation: "Family is everything." },
    ],
  },
  // Akan (Twi) course-11: Ananse the spider stories
  {
    id: "lesson-27",
    courseId: "course-11",
    title: "Ananse Visits Grandmother",
    description: "The trickster Ananse visits his grandmother — learn greetings through an Akan folktale.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    duration: 30,
    order: 1,
    completed: false,
    transcript: TRANSCRIPT_AKAN_1,
  },
  {
    id: "lesson-28",
    courseId: "course-11",
    title: "Ananse Counts His Treasures",
    description: "Ananse tries to count his treasures but keeps losing track — learning numbers in Twi.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    duration: 190,
    order: 2,
    completed: false,
    transcript: [
      { id: "tk28-1", startTime: 0, endTime: 0, text: "Me nneɛma! Momma menkane! Baako, mmienu, mmiɛnsa...", translation: "My treasures! Let me count! One, two, three..." },
      { id: "tk28-2", startTime: 0, endTime: 0, text: "Ɛnan, enum, nsia, nson, nwɔtwe", translation: "Four, five, six, seven, eight" },
      { id: "tk28-3", startTime: 0, endTime: 0, text: "Nkron, edu! Edu! Me wɔ edu!", translation: "Nine, ten! Ten! I have ten!" },
      { id: "tk28-4", startTime: 0, endTime: 0, text: "Ananse, wo mane no! Wo hwerɛɛ baako!", translation: "Ananse, you are confused! You lost one!" },
      { id: "tk28-5", startTime: 0, endTime: 0, text: "Dubaako, dumienu... aduonu!", translation: "Eleven, twelve... twenty!" },
      { id: "tk28-6", startTime: 0, endTime: 0, text: "Adeɛ a ɛho hia ne nyansa, ɛnyɛ sika.", translation: "What matters is wisdom, not wealth." },
    ],
  },
  {
    id: "lesson-29",
    courseId: "course-11",
    title: "Ananse and the Abusua",
    description: "Ananse discovers the meaning of abusua — family — when he needs help carrying food home.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    duration: 215,
    order: 3,
    completed: false,
    transcript: [
      { id: "tk29-1", startTime: 0, endTime: 0, text: "Boa me! Me ntumi mfa aduane yi nkɔ fie!", translation: "Help me! I cannot carry this food home!" },
      { id: "tk29-2", startTime: 0, endTime: 0, text: "Me agya bɛboa wo — father. Me na bɛboa wo — mother.", translation: "My father will help you. My mother will help you." },
      { id: "tk29-3", startTime: 0, endTime: 0, text: "Me nua barima — brother. Me nua bea — sister.", translation: "My brother. My sister." },
      { id: "tk29-4", startTime: 0, endTime: 0, text: "Nana bea — grandmother. Nana barima — grandfather.", translation: "Grandmother. Grandfather." },
      { id: "tk29-5", startTime: 0, endTime: 0, text: "Ananse! Wobɛhunu sɛ abusua yɛ den!", translation: "Ananse! You see that family is strong!" },
      { id: "tk29-6", startTime: 0, endTime: 0, text: "Medaase paa! Abusua yɛ ade a ɛho hia paa.", translation: "Thank you very much! Family is the most important thing." },
    ],
  },
  // Wolof course-12: A griot's feast of teranga (Senegalese hospitality)
  {
    id: "lesson-30",
    courseId: "course-12",
    title: "The Griot's Welcome",
    description: "A griot welcomes travelers to a teranga feast — learn Wolof greetings through Senegalese hospitality.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    duration: 30,
    order: 1,
    completed: false,
    transcript: TRANSCRIPT_WOLOF_1,
  },
  {
    id: "lesson-31",
    courseId: "course-12",
    title: "Haggling in Sandaga",
    description: "A visitor learns to count and bargain at Dakar's famous Sandaga market.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    duration: 185,
    order: 2,
    completed: false,
    transcript: [
      { id: "tw31-1", startTime: 0, endTime: 0, text: "Kaay Sandaga! Ndax bëgg ngay jënd?", translation: "Come to Sandaga! Do you want to buy?" },
      { id: "tw31-2", startTime: 0, endTime: 0, text: "Benn, ñaar, ñett, ñeent, juróom", translation: "One, two, three, four, five" },
      { id: "tw31-3", startTime: 0, endTime: 0, text: "Juróom-benn, juróom-ñaar, juróom-ñett, juróom-ñeent, fukk", translation: "Six, seven, eight, nine, ten" },
      { id: "tw31-4", startTime: 0, endTime: 0, text: "Ñaata lay jar? — Fukk ak juróom dërëm", translation: "How much does it cost? — Fifteen francs" },
      { id: "tw31-5", startTime: 0, endTime: 0, text: "Dafa seer! Wàccal ko tuuti!", translation: "It is expensive! Lower the price a bit!" },
      { id: "tw31-6", startTime: 0, endTime: 0, text: "Waaw, fukk. Jërëjëf!", translation: "Okay, ten. Thank you!" },
    ],
  },
  // Egyptian Arabic course-13: A traveler in old Cairo
  {
    id: "lesson-32",
    courseId: "course-13",
    title: "Youssef in Old Cairo",
    description: "Youssef visits a cafe in Cairo's old quarter and chats with the owner — learning greetings.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    duration: 30,
    order: 1,
    completed: false,
    transcript: TRANSCRIPT_ARABIC_EG_1,
  },
  {
    id: "lesson-33",
    courseId: "course-13",
    title: "Bargaining in Khan el-Khalili",
    description: "Youssef haggles for souvenirs in Cairo's oldest bazaar — counting and prices in Egyptian Arabic.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    duration: 195,
    order: 2,
    completed: false,
    transcript: [
      { id: "tae33-1", startTime: 0, endTime: 0, text: "أهلاً يا بيه! عايز تشتري إيه?", translation: "Welcome sir! What do you want to buy?" },
      { id: "tae33-2", startTime: 0, endTime: 0, text: "واحد، اتنين، تلاتة، أربعة، خمسة", translation: "One, two, three, four, five" },
      { id: "tae33-3", startTime: 0, endTime: 0, text: "ستة، سبعة، تمانية، تسعة، عشرة", translation: "Six, seven, eight, nine, ten" },
      { id: "tae33-4", startTime: 0, endTime: 0, text: "الفانوس ده بكام? — عشرين جنيه", translation: "How much is this lantern? — Twenty pounds" },
      { id: "tae33-5", startTime: 0, endTime: 0, text: "غالي! عشرة? — خلاص، خمستاشر", translation: "Expensive! Ten? — Okay, fifteen" },
      { id: "tae33-6", startTime: 0, endTime: 0, text: "شكراً! خان الخليلي حاجة تانية!", translation: "Thanks! Khan el-Khalili is something else!" },
    ],
  },
  {
    id: "lesson-34",
    courseId: "course-13",
    title: "Iftar with the Family",
    description: "Youssef joins an Egyptian family for iftar — learning family words during Ramadan.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    duration: 210,
    order: 3,
    completed: false,
    transcript: [
      { id: "tae34-1", startTime: 0, endTime: 0, text: "أهلاً وسهلاً! تعال كُل معانا الفطار", translation: "Welcome! Come eat iftar with us" },
      { id: "tae34-2", startTime: 0, endTime: 0, text: "ده أبويا — baba. ودي أمي — mama", translation: "This is my father — baba. This is my mother — mama" },
      { id: "tae34-3", startTime: 0, endTime: 0, text: "أخويا الكبير أحمد. وأختي الصغيرة نورا", translation: "My older brother Ahmed. And my little sister Noura" },
      { id: "tae34-4", startTime: 0, endTime: 0, text: "تيتا — grandmother. جدو — grandfather", translation: "Grandmother. Grandfather" },
      { id: "tae34-5", startTime: 0, endTime: 0, text: "العيلة كلها هنا! رمضان كريم!", translation: "The whole family is here! Ramadan Kareem!" },
      { id: "tae34-6", startTime: 0, endTime: 0, text: "شكراً جزيلاً! العيلة دي حاجة جميلة", translation: "Thank you so much! This family is something beautiful" },
    ],
  },
  // Somali course-14: A nomad's journey with the camel caravan
  {
    id: "lesson-35",
    courseId: "course-14",
    title: "The Camel Herder's Welcome",
    description: "A young herder greets travelers joining his family's camel caravan across the Somali plains.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    duration: 180,
    order: 1,
    completed: false,
    transcript: [
      { id: "tso35-1", startTime: 0, endTime: 0, text: "Iska warran! Soo dhawoow!", translation: "How are you! Come closer!" },
      { id: "tso35-2", startTime: 0, endTime: 0, text: "Magacaygu waa Cabdi. Adiga?", translation: "My name is Abdi. And you?" },
      { id: "tso35-3", startTime: 0, endTime: 0, text: "Waan fiicnahay! Xaggee baad u socotaa?", translation: "I am fine! Where are you going?" },
      { id: "tso35-4", startTime: 0, endTime: 0, text: "Waxaan raacayaa geelka. Waa safar dheer.", translation: "I am following the camels. It is a long journey." },
      { id: "tso35-5", startTime: 0, endTime: 0, text: "Kaalay, cunto naga cun! Soomaali waa martiqaad.", translation: "Come, eat with us! Somalis are hospitable." },
      { id: "tso35-6", startTime: 0, endTime: 0, text: "Mahadsanid! Nabad gelyo!", translation: "Thank you! Peace be with you!" },
    ],
  },
  {
    id: "lesson-36",
    courseId: "course-14",
    title: "Counting the Herd",
    description: "Abdi teaches a traveler to count camels and goats in Somali.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    duration: 185,
    order: 2,
    completed: false,
    transcript: [
      { id: "tso36-1", startTime: 0, endTime: 0, text: "Kaalay, aan tirino geelka! Kow, laba, saddex...", translation: "Come, let's count the camels! One, two, three..." },
      { id: "tso36-2", startTime: 0, endTime: 0, text: "Afar, shan, lix, toddobo, siddeed", translation: "Four, five, six, seven, eight" },
      { id: "tso36-3", startTime: 0, endTime: 0, text: "Sagaal, toban! Toban geel!", translation: "Nine, ten! Ten camels!" },
      { id: "tso36-4", startTime: 0, endTime: 0, text: "Riyaha — the goats — labaatan!", translation: "The goats — twenty!" },
      { id: "tso36-5", startTime: 0, endTime: 0, text: "Waa ku filan tahay. Xoolaha waa maal.", translation: "That is enough. Livestock is wealth." },
      { id: "tso36-6", startTime: 0, endTime: 0, text: "Rag waa geela loo tiriyaa. A man is measured by his camels.", translation: "A man is measured by his camels." },
    ],
  },
  // Bambara course-15: Under the palaver tree in Mali
  {
    id: "lesson-37",
    courseId: "course-15",
    title: "Under the Palaver Tree",
    description: "Two friends meet under the village palaver tree and exchange the elaborate Bambara greetings.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    duration: 185,
    order: 1,
    completed: false,
    transcript: [
      { id: "tb37-1", startTime: 0, endTime: 0, text: "I ni sogoma! I ka kɛnɛ wa?", translation: "Good morning! Are you well?" },
      { id: "tb37-2", startTime: 0, endTime: 0, text: "Nba! Tɔɔrɔ si tɛ. I ka kɛnɛ wa?", translation: "Yes! No trouble. Are you well?" },
      { id: "tb37-3", startTime: 0, endTime: 0, text: "Tɔɔrɔ si tɛ. I somɔgɔw ka kɛnɛ wa?", translation: "No trouble. Is your family well?" },
      { id: "tb37-4", startTime: 0, endTime: 0, text: "U bɛɛ ka kɛnɛ! I tɔgɔ?", translation: "They are all well! Your name?" },
      { id: "tb37-5", startTime: 0, endTime: 0, text: "N tɔgɔ ye Moussa. Aw ni baara!", translation: "My name is Moussa. Well done on your work!" },
      { id: "tb37-6", startTime: 0, endTime: 0, text: "I ni cɛ! Ala ka an kisi!", translation: "Thank you! May God protect us!" },
    ],
  },
  {
    id: "lesson-38",
    courseId: "course-15",
    title: "The Millet Harvest",
    description: "Moussa helps count sacks of millet during harvest — learning Bambara numbers.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    duration: 190,
    order: 2,
    completed: false,
    transcript: [
      { id: "tb38-1", startTime: 0, endTime: 0, text: "Moussa, nyɔ bolow jate! Kelen, fila, saba...", translation: "Moussa, count the millet sacks! One, two, three..." },
      { id: "tb38-2", startTime: 0, endTime: 0, text: "Naani, duuru, wɔɔrɔ, wolonfila, seegi", translation: "Four, five, six, seven, eight" },
      { id: "tb38-3", startTime: 0, endTime: 0, text: "Kɔnɔntɔn, tan! Bolo tan!", translation: "Nine, ten! Ten sacks!" },
      { id: "tb38-4", startTime: 0, endTime: 0, text: "A ka nyi! Mugan sisan!", translation: "Good! Twenty now!" },
      { id: "tb38-5", startTime: 0, endTime: 0, text: "Sisan an ka tila ka di dugu bɛɛ ma.", translation: "Now let us share and give to the whole village." },
      { id: "tb38-6", startTime: 0, endTime: 0, text: "Badenya ye baara ye. Brotherhood is work.", translation: "Brotherhood is work." },
    ],
  },
  // Tamazight course-16: An Amazigh grandmother's stories in the Atlas mountains
  {
    id: "lesson-39",
    courseId: "course-16",
    title: "Grandmother's Mountain Home",
    description: "A grandchild arrives at an Amazigh village in the Atlas mountains — learning Tamazight greetings.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    duration: 180,
    order: 1,
    completed: false,
    transcript: [
      { id: "tz39-1", startTime: 0, endTime: 0, text: "Azul! Amek tettiliḍ?", translation: "Hello! How are you?" },
      { id: "tz39-2", startTime: 0, endTime: 0, text: "Labas, tanemmirt! Isem inu Yidir.", translation: "Fine, thank you! My name is Yidir." },
      { id: "tz39-3", startTime: 0, endTime: 0, text: "Anida teddireḍ? — Di Tizi Ouzou.", translation: "Where do you live? — In Tizi Ouzou." },
      { id: "tz39-4", startTime: 0, endTime: 0, text: "Yemma tamɣart, usiɣ-d ɣur-m!", translation: "Grandmother, I have come to you!" },
      { id: "tz39-5", startTime: 0, endTime: 0, text: "Ansuf yis-k, amɣar inu! Axxam agi d axxam-ik.", translation: "Welcome, my child! This house is your house." },
      { id: "tz39-6", startTime: 0, endTime: 0, text: "Tanemmirt! D ayen i wumi qqareɣ axxam.", translation: "Thank you! This is what I call home." },
    ],
  },
  {
    id: "lesson-40",
    courseId: "course-16",
    title: "Counting Olives in the Grove",
    description: "Yidir and his grandmother count the olive harvest — learning Tamazight numbers.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    duration: 190,
    order: 2,
    completed: false,
    transcript: [
      { id: "tz40-1", startTime: 0, endTime: 0, text: "Yidir, ḥseb tazemmurt! Yiwen, sin, kraḍ...", translation: "Yidir, count the olive trees! One, two, three..." },
      { id: "tz40-2", startTime: 0, endTime: 0, text: "Kkuẓ, semmus, sḍis, sa, tam", translation: "Four, five, six, seven, eight" },
      { id: "tz40-3", startTime: 0, endTime: 0, text: "Tẓa, mraw! Mraw n tzemmurin!", translation: "Nine, ten! Ten olive trees!" },
      { id: "tz40-4", startTime: 0, endTime: 0, text: "Mraw d sin, mraw d kraḍ... sin d mraw!", translation: "Twelve, thirteen... twenty!" },
      { id: "tz40-5", startTime: 0, endTime: 0, text: "D ayla-nneɣ aya. Seg zik d ass-a.", translation: "This is our heritage. From ancient times to today." },
      { id: "tz40-6", startTime: 0, endTime: 0, text: "Tamazight d tutlayt n yizuran. It is the language of our roots.", translation: "Tamazight is the language of our roots." },
    ],
  },
  // Kinyarwanda course-17: A new student at an umuganda community work day
  {
    id: "lesson-41",
    courseId: "course-17",
    title: "Umuganda Morning",
    description: "A newcomer joins an umuganda community work day — learning Kinyarwanda greetings.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    duration: 180,
    order: 1,
    completed: false,
    transcript: [
      { id: "trw41-1", startTime: 0, endTime: 0, text: "Muraho! Amakuru?", translation: "Hello! How are you?" },
      { id: "trw41-2", startTime: 0, endTime: 0, text: "Ni meza! Nitwa Uwimana. Nawe?", translation: "Fine! My name is Uwimana. And you?" },
      { id: "trw41-3", startTime: 0, endTime: 0, text: "Nitwa Keza. Ubu ni umuganda?", translation: "My name is Keza. Is today umuganda?" },
      { id: "trw41-4", startTime: 0, endTime: 0, text: "Yego! Twese dukorera hamwe.", translation: "Yes! We all work together." },
      { id: "trw41-5", startTime: 0, endTime: 0, text: "Ubumwe ni amahoro. Unity is peace.", translation: "Unity is peace." },
      { id: "trw41-6", startTime: 0, endTime: 0, text: "Murakoze cyane! Mwiriwe neza!", translation: "Thank you so much! Good evening!" },
    ],
  },
  {
    id: "lesson-42",
    courseId: "course-17",
    title: "Planting Together",
    description: "Uwimana and Keza count seedlings during an umuganda tree-planting — learning numbers.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    duration: 185,
    order: 2,
    completed: false,
    transcript: [
      { id: "trw42-1", startTime: 0, endTime: 0, text: "Keza, tubale ibiti! Rimwe, kabiri, gatatu...", translation: "Keza, let's plant trees! One, two, three..." },
      { id: "trw42-2", startTime: 0, endTime: 0, text: "Kane, gatanu, gatandatu, karindwi, umunani", translation: "Four, five, six, seven, eight" },
      { id: "trw42-3", startTime: 0, endTime: 0, text: "Icyenda, icumi! Ibiti icumi!", translation: "Nine, ten! Ten trees!" },
      { id: "trw42-4", startTime: 0, endTime: 0, text: "Cumi na rimwe, cumi na kabiri... makumyabiri!", translation: "Eleven, twelve... twenty!" },
      { id: "trw42-5", startTime: 0, endTime: 0, text: "Igiti cyawe, igiti cyanjye — twese turabiteramo.", translation: "Your tree, my tree — we all share in them." },
      { id: "trw42-6", startTime: 0, endTime: 0, text: "Agaciro k'umuganda ni uko dukorera hamwe.", translation: "The value of umuganda is that we work together." },
    ],
  },
  // Ewe course-18: A drummer prepares for a festival in the Volta Region
  {
    id: "lesson-43",
    courseId: "course-18",
    title: "The Drummer's Festival",
    description: "A young drummer prepares for the Hogbetsotso festival — learning Ewe greetings.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    duration: 185,
    order: 1,
    completed: false,
    transcript: [
      { id: "te43-1", startTime: 0, endTime: 0, text: "Ŋdi na mi! Aleke nènye?", translation: "Good morning! How are you?" },
      { id: "te43-2", startTime: 0, endTime: 0, text: "Nyɛ nkɔ nye Kofi. Mele nyuie.", translation: "My name is Kofi. I am well." },
      { id: "te43-3", startTime: 0, endTime: 0, text: "Egbe nye Hogbetsotso ŋkeke!", translation: "Today is Hogbetsotso festival day!" },
      { id: "te43-4", startTime: 0, endTime: 0, text: "Míaƒe togbui siwo ŋu mía da ŋu le.", translation: "We are honoring our ancestors." },
      { id: "te43-5", startTime: 0, endTime: 0, text: "Kofi, va! Àdzo vu lɔ̃ na wò!", translation: "Kofi, come! The drums are calling you!" },
      { id: "te43-6", startTime: 0, endTime: 0, text: "Akpe na mi! Hede nyuie!", translation: "Thank you! Have a good evening!" },
    ],
  },
  {
    id: "lesson-44",
    courseId: "course-18",
    title: "Counting Drumbeats",
    description: "Kofi's teacher helps him keep rhythm by counting beats in Ewe.",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    duration: 190,
    order: 2,
    completed: false,
    transcript: [
      { id: "te44-1", startTime: 0, endTime: 0, text: "Kofi, lã vu! Ɖeka, eve, etɔ̃...", translation: "Kofi, hit the drum! One, two, three..." },
      { id: "te44-2", startTime: 0, endTime: 0, text: "Enɛ, atɔ̃, adre, adrɛ, enyi", translation: "Four, five, six, seven, eight" },
      { id: "te44-3", startTime: 0, endTime: 0, text: "Asieke, ewo! Ewo vu!", translation: "Nine, ten! Ten beats!" },
      { id: "te44-4", startTime: 0, endTime: 0, text: "Wuieve, wuietɔ̃... blaeve!", translation: "Eleven, twelve... twenty!" },
      { id: "te44-5", startTime: 0, endTime: 0, text: "Nyuie! Vu ƒe gbe nye míaƒe gbe.", translation: "Good! The voice of the drum is our voice." },
      { id: "te44-6", startTime: 0, endTime: 0, text: "Akpe, dada! Mala bɔ.", translation: "Thank you, master! I will keep learning." },
    ],
  },
  // Izon course-19: Sounds & Spelling — Grandmother teaches grandchild to read the old stories
  {
    id: "lesson-45",
    courseId: "course-19",
    title: "Vowel Harmony",
    description: "A grandmother teaches her grandchild to read Izon by exploring how vowels work together in the Woyengi creation story.",
    order: 1,
    completed: false,
    transcript: [
      { id: "t45-1", startTime: 0, endTime: 0, text: "Nene, ẹmẹnẹ Izon tị kịmị fịrị ye-a?", translation: "Grandma, how do Izon letters work?" },
      { id: "t45-2", startTime: 0, endTime: 0, text: "Bo dẹkị, tau. Tẹmẹ kẹnị ka. Anị arụ ye oyi mọ isẹ — a e i o u ẹ ị ọ ụ.", translation: "Come, grandchild. Let me show you. Our mouths hold nine sounds — a e i o u ẹ ị ọ ụ." },
      { id: "t45-3", startTime: 0, endTime: 0, text: "Isẹ! Ẹndẹị yẹ-a? Oyingi bẹrẹịn ọfa ye-a?", translation: "Nine! Why so many? Did Woyengi make them all?" },
      { id: "t45-4", startTime: 0, endTime: 0, text: "Ee! Wide vowels — i, e, o, u — timi kẹnị arụ ye fịrị.", translation: "Yes! The wide vowels — i, e, o, u — they work together like friends." },
      { id: "t45-5", startTime: 0, endTime: 0, text: "Mọ narrow vowels — ị, ẹ, ọ, ụ — timi kẹnị arụ ye fịrị.", translation: "And the narrow vowels — ị, ẹ, ọ, ụ — they also group together." },
      { id: "t45-6", startTime: 0, endTime: 0, text: "Obori sei! Wide — o mọ i timi kẹnị ye.", translation: "Say 'obori' (goat)! Wide — o and i stay together." },
      { id: "t45-7", startTime: 0, endTime: 0, text: "Mọ fịrị? Ị mọ ị — narrow timi kẹnị ye!", translation: "And 'fịrị' (work)? Ị and ị — narrow ones stay together!" },
      { id: "t45-8", startTime: 0, endTime: 0, text: "Kịịrịị! Ele — e mọ e, wide. Kọrọ — ọ mọ ọ, narrow.", translation: "Correct! 'Ele' (gorilla) — e and e, wide. 'Kọrọ' (raphia palm) — ọ and ọ, narrow." },
      { id: "t45-9", startTime: 0, endTime: 0, text: "Nene, mọ 'a' tị-a? Aba tị kẹnị ye emi.", translation: "Grandma, what about 'a'? It appears in 'aba' (fish)." },
      { id: "t45-10", startTime: 0, endTime: 0, text: "'A' ye neutral — timi ọfa mọ fịrị. Pẹlẹ — ẹ mọ ẹ, narrow. Anị tẹmẹ ka emi!", translation: "'A' is neutral — it works with everyone. 'Pẹlẹ' (to cut) — ẹ and ẹ, narrow. Now you see the pattern!" },
    ],
  },
  {
    id: "lesson-46",
    courseId: "course-19",
    title: "Consonants & Digraphs",
    description: "Grandmother and grandchild explore Izon consonants through a story about the Ekine masquerade preparations.",
    order: 2,
    completed: false,
    transcript: [
      { id: "t46-1", startTime: 0, endTime: 0, text: "Nene, Ekine ama-a bo emi! Tẹmẹ kẹnị tị arụ ye sei-a?", translation: "Grandma, the Ekine masquerade is coming! What sounds do we need to know?" },
      { id: "t46-2", startTime: 0, endTime: 0, text: "Anị arụ ye consonants — p, b, t, d, k, g, m, n, f, s. Pa — appear! Ba — strike!", translation: "Our sounds are the consonants — p, b, t, d, k, g, m, n, f, s. 'Pa' — appear! 'Ba' — strike!" },
      { id: "t46-3", startTime: 0, endTime: 0, text: "Ka — be mature. Kịmị ka emi mene Ekine fịrị bọ.", translation: "'Ka' — be mature. A person must be mature before Ekine work begins." },
      { id: "t46-4", startTime: 0, endTime: 0, text: "Nene, mọ 'gh' tị-a? Bogha — bogha ye ẹndẹị-a?", translation: "Grandma, what about 'gh'? 'Bogha' — what does 'bogha' mean?" },
      { id: "t46-5", startTime: 0, endTime: 0, text: "Bogha — did not come. 'Gh' ye very soft, like breath. Aghain — no.", translation: "'Bogha' — did not come. 'Gh' is very soft, like a breath. 'Aghain' — no." },
      { id: "t46-6", startTime: 0, endTime: 0, text: "Mọ 'nghi'? Bonghi — will come! Ekine bonghi!", translation: "And 'nghi'? 'Bonghi' — will come! The masquerade will come!" },
      { id: "t46-7", startTime: 0, endTime: 0, text: "Gbein! Anị gbein owuamapu tẹmẹ. 'Gb' ye kẹnị arụ — mouth mọ throat timi.", translation: "'Gbein' — throw! We throw the water spirit's image. 'Gb' is one sound — mouth and throat together." },
      { id: "t46-8", startTime: 0, endTime: 0, text: "Kpapụ — scissors! 'Kp' ye like 'gb' — ma arụ kẹnị ye.", translation: "'Kpapụ' — scissors! 'Kp' is like 'gb' — two sounds become one." },
      { id: "t46-9", startTime: 0, endTime: 0, text: "Haan! Hiin! 'H' ye exclamation arụ ọnị. Ọfa anị sei bọ.", translation: "'Haan! Hiin!' — 'H' only appears in exclamations. It's not in regular words." },
      { id: "t46-10", startTime: 0, endTime: 0, text: "Nene, Izon kịịrịị ye! Words ye as you sei them — ba, ka, la!", translation: "Grandma, Izon is honest! Words are spelled as you say them — ba, ka, la!" },
    ],
  },
  {
    id: "lesson-47",
    courseId: "course-19",
    title: "Nasalized & Long Vowels",
    description: "By the river at dusk, grandmother teaches how nasal sounds and long vowels carry meaning in Izon songs and stories.",
    order: 3,
    completed: false,
    transcript: [
      { id: "t47-1", startTime: 0, endTime: 0, text: "Nene, beni furu ye singing emi. Ẹndẹị yẹ arụ ye long-a?", translation: "Grandma, the river women are singing. Why do some sounds stretch long?" },
      { id: "t47-2", startTime: 0, endTime: 0, text: "Tau, kẹnị arụ ye nasal — 'n' ye end tị. Kan — to wander. Kan beni beị mọ.", translation: "Grandchild, some sounds are nasal — 'n' sits at the end. 'Kan' — to wander. To wander by the river." },
      { id: "t47-3", startTime: 0, endTime: 0, text: "Geen — be brightly lit! Owuamapu geen tị beni ama!", translation: "'Geen' — to be brightly lit! The water spirits shine on the river!" },
      { id: "t47-4", startTime: 0, endTime: 0, text: "Sẹẹn — to shave. Warriors sẹẹn before Egbesu festival.", translation: "'Sẹẹn' — to shave. Warriors shave before the Egbesu festival." },
      { id: "t47-5", startTime: 0, endTime: 0, text: "Pin — be crowded. Kịmị pin emi festival tị!", translation: "'Pin' — to be crowded. The people are crowded at the festival!" },
      { id: "t47-6", startTime: 0, endTime: 0, text: "Mọ pịn — to tap palm wine. Dau ẹmẹnẹ pịn ye kọrọ tị!", translation: "And 'pịn' — to tap palm wine. Father is tapping wine from the raphia palm!" },
      { id: "t47-7", startTime: 0, endTime: 0, text: "Tọn — to measure. Sụn — to stretch. Cloth tọn mọ sụn for masquerade.", translation: "'Tọn' — to measure. 'Sụn' — to stretch. Measure and stretch cloth for the masquerade." },
      { id: "t47-8", startTime: 0, endTime: 0, text: "Now tau, long vowels — double the letter! Baaraa vs Bara.", translation: "Now grandchild, long vowels — you double the letter! 'Baaraa' vs 'Bara'." },
      { id: "t47-9", startTime: 0, endTime: 0, text: "Baaraa — dry season, when beni ye low. Bara — hand, for holding paddle.", translation: "'Baaraa' — the dry season, when the river is low. 'Bara' — a hand, for holding a paddle." },
      { id: "t47-10", startTime: 0, endTime: 0, text: "Kịịrịị — be correct! Kịrị — to slice fish. Length dei meaning!", translation: "'Kịịrịị' — to be correct! 'Kịrị' — to slice fish. The length changes the meaning!" },
    ],
  },
  {
    id: "lesson-48",
    courseId: "course-19",
    title: "Vowel Sequences",
    description: "Grandmother and grandchild paddle their canoe while practicing the vowel pairs that make Izon unique.",
    order: 4,
    completed: false,
    transcript: [
      { id: "t48-1", startTime: 0, endTime: 0, text: "Nene, canoe tị, ẹmẹnẹ practice bọ-a?", translation: "Grandma, can we practice in the canoe?" },
      { id: "t48-2", startTime: 0, endTime: 0, text: "Ee! Izon vowels ye separate — no diphthongs. Dau — father. Tau — grandchild. You sei each vowel.", translation: "Yes! Izon vowels stay separate — no diphthongs. 'Dau' — father. 'Tau' — grandchild. You say each vowel clearly." },
      { id: "t48-3", startTime: 0, endTime: 0, text: "Dau! Tau! Anị timi ye — dau mọ tau canoe tị emi!", translation: "'Dau! Tau!' — We are together — father and grandchild in the canoe!" },
      { id: "t48-4", startTime: 0, endTime: 0, text: "Tẹị — to escape. Sẹị — to dance! Owuamapu sẹị beni tị!", translation: "'Tẹị' — to escape. 'Sẹị' — to dance! The water spirits dance on the river!" },
      { id: "t48-5", startTime: 0, endTime: 0, text: "Dei — to change. Sei — be bad. Beni dei, but beni bogha sei.", translation: "'Dei' — to change. 'Sei' — be bad. The river changes, but the river is not bad." },
      { id: "t48-6", startTime: 0, endTime: 0, text: "Pou — to press down. Sou — to dig. Fisherman pou net mọ sou sand.", translation: "'Pou' — to press down. 'Sou' — to dig. The fisherman presses the net and digs the sand." },
      { id: "t48-7", startTime: 0, endTime: 0, text: "Nene, pọụ mọ sọụ tị-a? Ẹmẹnẹ pọụ ye cloth, sọụ ye plants!", translation: "Grandma, what about 'pọụ' and 'sọụ'? 'Pọụ' is washing cloth, 'sọụ' is growing plants!" },
      { id: "t48-8", startTime: 0, endTime: 0, text: "Kịịrịị! Tuo — grass by the river. Tụọ — to cook the fish we catch!", translation: "Correct! 'Tuo' — grass by the river. 'Tụọ' — to cook the fish we catch!" },
      { id: "t48-9", startTime: 0, endTime: 0, text: "Kaịn — be torn. Mọ net kaịn emi! Kịén — to count. Kịén anị aba!", translation: "'Kaịn' — be torn. Our net is torn! 'Kịén' — to count. Count our fish!" },
      { id: "t48-10", startTime: 0, endTime: 0, text: "Nene, English 'train' — anị sei 'tireni'! No consonant clusters!", translation: "Grandma, the English word 'train' — we say 'tireni'! No consonant clusters!" },
    ],
  },
  // Izon course-20: Numbers & Money — Father teaches son to count the fishing catch and trade at market
  {
    id: "lesson-49",
    courseId: "course-20",
    title: "Counting 1–20",
    description: "A father teaches his son to count fish from their catch, using both modern and traditional Izon numbers.",
    order: 1,
    completed: false,
    transcript: [
      { id: "t49-1", startTime: 0, endTime: 0, text: "Dau, anị aba kịén bọ! Canoe ye full emi!", translation: "Father, let's count our fish! The canoe is full!" },
      { id: "t49-2", startTime: 0, endTime: 0, text: "Ee, tau. Empty basket first — odo. Éyéfá. Zero fish.", translation: "Yes, son. Empty basket first — 'odo'. 'Éyéfá'. Zero fish." },
      { id: "t49-3", startTime: 0, endTime: 0, text: "Kẹnị aba! One fish in the basket. Mamu — two! Taru — three!", translation: "'Kẹnị' fish! One fish in the basket. 'Mamu' — two! 'Taru' — three!" },
      { id: "t49-4", startTime: 0, endTime: 0, text: "Nein aba — four fish! Sọrọn — five! One hand full.", translation: "'Nein' fish — four fish! 'Sọrọn' — five! One hand is full." },
      { id: "t49-5", startTime: 0, endTime: 0, text: "Sendie — six, Sọnọma — seven, Niina — eight, Ise — nine!", translation: "'Sendie' — six, 'Sọnọma' — seven, 'Niina' — eight, 'Ise' — nine!" },
      { id: "t49-6", startTime: 0, endTime: 0, text: "Oyi! Ten fish, tau! Basket kẹnị ye full.", translation: "'Oyi'! Ten fish, son! The first basket is full." },
      { id: "t49-7", startTime: 0, endTime: 0, text: "Dau, more aba ye emi! Oyi kẹnị fini — eleven!", translation: "Father, there are more fish! 'Oyi kẹnị fini' — eleven!" },
      { id: "t49-8", startTime: 0, endTime: 0, text: "Oyi mamu fini — twelve. Oyi taru fini — thirteen. Pattern ka emi!", translation: "'Oyi mamu fini' — twelve. 'Oyi taru fini' — thirteen. You see the pattern!" },
      { id: "t49-9", startTime: 0, endTime: 0, text: "Oyi sọrọn fini — fifteen! Anị sei 'die' bọ — die ye fifteen!", translation: "'Oyi sọrọn fini' — fifteen! We can also say 'die' — 'die' means fifteen!" },
      { id: "t49-10", startTime: 0, endTime: 0, text: "Sí! Twenty fish! Sí ye big number — anị hands mọ feet ọfa!", translation: "'Sí'! Twenty fish! 'Sí' is a big number — all our fingers and toes!" },
    ],
  },
  {
    id: "lesson-50",
    courseId: "course-20",
    title: "Counting 21–100",
    description: "Father and son count a large catch of fish, learning the traditional Izon system of counting by twenties.",
    order: 2,
    completed: false,
    transcript: [
      { id: "t50-1", startTime: 0, endTime: 0, text: "Dau! Beni ye good today — aba ye plenty! More than sí!", translation: "Father! The river was good today — so many fish! More than twenty!" },
      { id: "t50-2", startTime: 0, endTime: 0, text: "Izon kịén ye vigesimal — anị count by twenties. Sí kẹnị feni — twenty-one!", translation: "Izon counting is vigesimal — we count by twenties. 'Sí kẹnị feni' — twenty-one!" },
      { id: "t50-3", startTime: 0, endTime: 0, text: "Sí oyi feni — thirty! Twenty mọ ten more. Aba plenty emi!", translation: "'Sí oyi feni' — thirty! Twenty and ten more. So many fish!" },
      { id: "t50-4", startTime: 0, endTime: 0, text: "Ma sí — forty. That's two twenties. Two people's fingers and toes!", translation: "'Ma sí' — forty. That's two twenties. Two people's fingers and toes!" },
      { id: "t50-5", startTime: 0, endTime: 0, text: "Masí mọ oyi mọ — fifty! Masí mọ kẹnị mọ — forty-one!", translation: "'Masí mọ oyi mọ' — fifty! 'Masí mọ kẹnị mọ' — forty-one!" },
      { id: "t50-6", startTime: 0, endTime: 0, text: "Tará sí — sixty! Three twenties. Anị aba ye kọr timi!", translation: "'Tará sí' — sixty! Three twenties. Our fish fill many baskets!" },
      { id: "t50-7", startTime: 0, endTime: 0, text: "Tara si oi fini — seventy. Nia sí — eighty! Four twenties!", translation: "'Tara si oi fini' — seventy. 'Nia sí' — eighty! Four twenties!" },
      { id: "t50-8", startTime: 0, endTime: 0, text: "Nia si oi fini — ninety. Almost there, tau!", translation: "'Nia si oi fini' — ninety. Almost there, son!" },
      { id: "t50-9", startTime: 0, endTime: 0, text: "Ọdọzọ! One hundred fish! Dau, anị ye rich today!", translation: "'Ọdọzọ'! One hundred fish! Father, we are rich today!" },
      { id: "t50-10", startTime: 0, endTime: 0, text: "Ogiza ye one thousand — but today ọdọzọ ye enough! Market bonghi!", translation: "'Ogiza' is one thousand — but today a hundred is enough! Time for market!" },
    ],
  },
  {
    id: "lesson-51",
    courseId: "course-20",
    title: "Money & Market",
    description: "Father and son take their fish to market, learning the traditional akpa money system and how to bargain.",
    order: 3,
    completed: false,
    transcript: [
      { id: "t51-1", startTime: 0, endTime: 0, text: "Dau, market emi! Ẹmẹnẹ anị aba sell bọ-a?", translation: "Father, we're at the market! How do we sell our fish?" },
      { id: "t51-2", startTime: 0, endTime: 0, text: "Tau, sẹlẹ — money. Kẹnị timi sei okubo, igbogi, okoba. All ye money.", translation: "Son, 'sẹlẹ' — money. Some people say 'okubo', 'igbogi', 'okoba'. All mean money." },
      { id: "t51-3", startTime: 0, endTime: 0, text: "Akpa — a bag. Traditional unit ye akpa. Akpa ekise — N100, half a bag.", translation: "'Akpa' — a bag. Our traditional unit is the bag. 'Akpa ekise' — N100, half a bag." },
      { id: "t51-4", startTime: 0, endTime: 0, text: "Akpa kẹnị — N200. Ma akpa — N400, two bags!", translation: "One 'akpa' — N200. 'Ma akpa' — N400, two bags!" },
      { id: "t51-5", startTime: 0, endTime: 0, text: "Tará akpa — N600. Sọọnran akpa — N1000, five bags!", translation: "'Tará akpa' — N600. 'Sọọnran akpa' — N1000, five bags!" },
      { id: "t51-6", startTime: 0, endTime: 0, text: "Oyi akpa — N2000! Dau, anị aba ye oyi akpa-a?", translation: "'Oyi akpa' — N2000! Father, are our fish worth ten bags?" },
      { id: "t51-7", startTime: 0, endTime: 0, text: "Woman: Yebị ẹndẹị? — How much for the fish?", translation: "A woman approaches: 'How much is it?'" },
      { id: "t51-8", startTime: 0, endTime: 0, text: "Dau: Sọọnran akpa — N1000 for ọfa aba.", translation: "Father: 'Five bags — N1000 for all the fish.'" },
      { id: "t51-9", startTime: 0, endTime: 0, text: "Woman: Tubobị Iyerimọ! Tará akpa?", translation: "Woman: 'Make it cheaper! Three bags (N600)?'" },
      { id: "t51-10", startTime: 0, endTime: 0, text: "Dau: Nein akpa — N800. Last price.", translation: "Father: 'Four bags — N800. Last price.'" },
      { id: "t51-11", startTime: 0, endTime: 0, text: "Woman: Ee! Okubo kọọr yọ kei ipiri — give me change. Tau, anị fịrị kịịrịị emi!", translation: "Woman: 'Yes! Give me my change.' Son, we did well today!" },
    ],
  },
];

export const SAMPLE_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: "j1",
    title: "First Lesson!",
    content: "Today I learned basic Izon greetings. 'Ọya bẹi sei' means Good morning! I find the tonal patterns interesting.",
    lessonId: "lesson-1",
    createdAt: "2025-01-15T10:30:00Z",
    updatedAt: "2025-01-15T10:30:00Z",
  },
  {
    id: "j2",
    title: "The Tortoise Story",
    content: "Listened to the tortoise folktale. The storytelling style is beautiful. I want to practice retelling it.",
    lessonId: "lesson-2",
    createdAt: "2025-01-16T14:00:00Z",
    updatedAt: "2025-01-16T14:00:00Z",
  },
];

export const SAMPLE_FEED: FeedItem[] = [
  {
    id: "f1",
    type: "lesson_completed",
    title: "Completed Greetings & Introductions",
    description: "Finished the first lesson in Izon Basics",
    userName: "Tamara A.",
    createdAt: "2025-01-15T10:30:00Z",
    likes: 5,
    comments: 2,
  },
  {
    id: "f2",
    type: "contribution",
    title: "New audio recording",
    description: "Contributed a pronunciation guide for common Yoruba greetings",
    userName: "Ebi O.",
    createdAt: "2025-01-14T16:00:00Z",
    likes: 12,
    comments: 4,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: "f3",
    type: "achievement",
    title: "7-day streak!",
    description: "Reached a 7-day learning streak across Izon and Yoruba",
    userName: "Diepreye K.",
    createdAt: "2025-01-13T09:00:00Z",
    likes: 20,
    comments: 8,
  },
  {
    id: "f4",
    type: "community",
    title: "Study group forming",
    description: "Looking for learners to practice conversational Igbo together on weekends",
    userName: "Seiyefa T.",
    createdAt: "2025-01-12T12:00:00Z",
    likes: 15,
    comments: 11,
  },
  {
    id: "f5",
    type: "lesson_completed",
    title: "Completed The Tortoise and the River",
    description: "Loved this traditional Izon folktale! The narrator's voice is captivating.",
    userName: "Boma D.",
    createdAt: "2025-01-11T18:00:00Z",
    likes: 8,
    comments: 3,
  },
  {
    id: "f6",
    type: "contribution",
    title: "Hausa translation added",
    description: "Translated 15 common phrases into Hausa with audio recordings",
    userName: "Amina B.",
    createdAt: "2025-01-10T11:00:00Z",
    likes: 18,
    comments: 6,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },
];

export const SAMPLE_COMMENTS: Comment[] = [
  // f1 comments
  { id: "c1", feedItemId: "f1", userName: "Ebi O.", text: "Great job! Keep it up!", createdAt: "2025-01-15T11:00:00Z" },
  { id: "c2", feedItemId: "f1", userName: "Diepreye K.", text: "The greetings lesson is one of my favourites", createdAt: "2025-01-15T12:30:00Z" },
  // f2 comments
  { id: "c3", feedItemId: "f2", userName: "Tamara A.", text: "This is so helpful, thank you!", createdAt: "2025-01-14T17:00:00Z" },
  { id: "c4", feedItemId: "f2", userName: "Seiyefa T.", text: "Your pronunciation is really clear", createdAt: "2025-01-14T18:00:00Z" },
  { id: "c5", feedItemId: "f2", userName: "Boma D.", text: "Can you do one for Igbo greetings too?", createdAt: "2025-01-14T19:00:00Z" },
  { id: "c6", feedItemId: "f2", userName: "Amina B.", text: "Shared this with my study group!", createdAt: "2025-01-14T20:00:00Z" },
  // f3 comments
  { id: "c7", feedItemId: "f3", userName: "Tamara A.", text: "Wow 7 days, amazing consistency!", createdAt: "2025-01-13T10:00:00Z" },
  { id: "c8", feedItemId: "f3", userName: "Ebi O.", text: "Inspiring! I'm on day 3 myself", createdAt: "2025-01-13T11:00:00Z" },
  // f4 comments
  { id: "c9", feedItemId: "f4", userName: "Diepreye K.", text: "Count me in! What time on weekends?", createdAt: "2025-01-12T13:00:00Z" },
  { id: "c10", feedItemId: "f4", userName: "Boma D.", text: "I'd love to join, I'm learning Igbo basics", createdAt: "2025-01-12T14:00:00Z" },
  // f5 comments
  { id: "c11", feedItemId: "f5", userName: "Seiyefa T.", text: "The narrator is incredible!", createdAt: "2025-01-11T19:00:00Z" },
  // f6 comments
  { id: "c12", feedItemId: "f6", userName: "Diepreye K.", text: "This is a huge contribution, thank you Amina!", createdAt: "2025-01-10T12:00:00Z" },
  { id: "c13", feedItemId: "f6", userName: "Tamara A.", text: "The audio quality is perfect", createdAt: "2025-01-10T13:00:00Z" },
];

export function getLanguageName(id: string): string {
  return LANGUAGES.find((l) => l.id === id)?.name ?? id;
}

export function getCoursesByLanguage(languageId: string): Course[] {
  return COURSES.filter((c) => c.language === languageId);
}

export function getLessonById(id: string): Lesson | undefined {
  return LESSONS.find((l) => l.id === id);
}

export function getLessonsByCourse(courseId: string): Lesson[] {
  return LESSONS.filter((l) => l.courseId === courseId);
}

export function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}
