// AUTO-GENERATED by populate-igbo-from-api.ts on 2026-06-11T23:10:52.126Z
// 3 entries fetched from igboapi.com — review before merging into igbo.ts
//
// To merge: copy the array entries into IGBO_DICTIONARY in igbo.ts,
// then run: cd server && npm run db:sync-dict
import type { DictionaryEntry } from "@/lib/dictionary";

export const IGBO_API_ENTRIES: DictionaryEntry[] = [
  { id: "d-ig-1000", word: "oo", english: "an expression of agreement to comply with a command or request; I or we will", category: "greetings", languageId: "igbo", englishWordId: "ew-3", pronunciation: "https://igbo-api.s3.us-east-2.amazonaws.com/audio-pronunciations/5f90c35f49f7e863e92b887a.mp3" },
  { id: "d-ig-1001", word: "akpụ", english: "cassava", category: "nouns", languageId: "igbo", englishWordId: "ew-8", pronunciation: "https://igbo-api.s3.us-east-2.amazonaws.com/audio-pronunciations/5f90c35e49f7e863e92b6ff0.mp3", nsibidi: "小" },
  { id: "d-ig-1002", word: "ọ̀tụtụ", english: "many; numerous; several; a lot", category: "adjectives", languageId: "igbo", englishWordId: "ew-16", pronunciation: "https://igbo-api.s3.us-east-2.amazonaws.com/audio-pronunciations/5f90c35f49f7e863e92b88aa.webm", nsibidi: "裁" },
];
