import type MaterialIcons from "@expo/vector-icons/MaterialIcons";
import type { SymbolViewProps } from "expo-symbols";
import type { ComponentProps } from "react";

/**
 * SF Symbol → Material Icons mapping, shared by both platform implementations of
 * `IconSymbol` so their `name` prop types cannot drift apart. It lives in its own
 * module because `icon-symbol.ios.tsx` cannot import from `icon-symbol.tsx` —
 * Metro's platform resolution would resolve that back to the `.ios` file itself.
 *
 * `Partial<>` + `satisfies` (rather than `as`) is load-bearing. `satisfies`
 * validates every value against the Material Icons glyph union while preserving
 * the inferred key literals, so `IconSymbolName` is the set of symbols we can
 * actually render. An `as` assertion here would widen `keyof typeof MAPPING`
 * back to all ~9,000 SF Symbol names — which is what used to happen, and why
 * dozens of unrenderable icons silently resolved to `undefined` on Android.
 *
 * Adding an icon means adding it here first. There is no fallback glyph by design:
 * a missing entry is a compile error, not a blank space in the UI.
 */
type IconMapping = Partial<
  Record<SymbolViewProps["name"], ComponentProps<typeof MaterialIcons>["name"]>
>;

export const MAPPING = {
  'house.fill': 'home',
  'paperplane.fill': 'send',
  'chevron.left.forwardslash.chevron.right': 'code',
  'chevron.right': 'chevron-right',
  'chevron.up': 'keyboard-arrow-up',
  'chevron.down': 'keyboard-arrow-down',
  'arrow.up.arrow.down': 'swap-vert',
  'exclamationmark.triangle.fill': 'warning',
  'book.fill': 'menu-book',
  'headphones': 'headphones',
  'pencil.and.list.clipboard': 'edit-note',
  'newspaper.fill': 'dynamic-feed',
  'person.fill': 'person',
  'play.fill': 'play-arrow',
  'pause.fill': 'pause',
  'speaker.wave.2.fill': 'volume-up',
  'forward.fill': 'forward-10',
  'backward.fill': 'replay-10',
  'gobackward.5': 'replay-5',
  'goforward.10': 'forward-10',
  'chevron.left': 'chevron-left',
  'arrow.down': 'south',
  'list.bullet': 'format-list-bulleted',
  'text.quote': 'format-quote',
  'leaf.fill': 'eco',
  'cross.case.fill': 'medical-services',
  'cloud.sun.fill': 'wb-cloudy',
  'person.2.fill': 'groups',
  'star': 'star-border',
  'star.slash': 'star-outline',
  'speedometer': 'speed',
  'checkmark.circle.fill': 'check-circle',
  'circle': 'radio-button-unchecked',
  'clock': 'access-time',
  'flame.fill': 'local-fire-department',
  'star.fill': 'star',
  'heart.fill': 'favorite',
  'heart': 'favorite-border',
  'plus': 'add',
  'xmark': 'close',
  'magnifyingglass': 'search',
  'arrow.down.circle': 'download',
  'ellipsis': 'more-horiz',
  'message': 'chat-bubble-outline',
  'hand.thumbsup': 'thumb-up',
  'chart.bar.fill': 'bar-chart',
  'gearshape.fill': 'settings',
  'square.and.arrow.up': 'share',
  'mic.fill': 'mic',
  'waveform': 'graphic-eq',
  'arrow.up.circle.fill': 'send',
  'text.bubble': 'forum',
  'character.book.closed': 'auto-stories',
  'graduationcap.fill': 'school',
  'shield.fill': 'verified-user',
  'clock.fill': 'access-time',
  'checkmark.seal.fill': 'verified',
  'xmark.circle.fill': 'cancel',
  'list.bullet.clipboard': 'edit-note',
  'photo': 'photo',
  'photo.badge.plus': 'add-photo-alternate',
  'plus.circle': 'add-circle-outline',
  'calendar': 'calendar-today',
  'person.badge.shield.checkmark.fill': 'admin-panel-settings',
  'bell.fill': 'notifications',
  'bell': 'notifications-none',
  'trophy.fill': 'emoji-events',
  'snowflake': 'ac-unit',
  'arrow.counterclockwise': 'refresh',
  'megaphone': 'campaign',
  'globe.fill': 'language',
  'play.circle.fill': 'play-circle',
  'doc.text.fill': 'article',
  'film.stack': 'video-library',
  'checkmark': 'check',
  'questionmark': 'help-outline',
  'square.on.square': 'content-copy',
  'lock.fill': 'lock',
  'crown.fill': 'workspace-premium',
  'shield.slash.fill': 'remove-moderator',
  'repeat.1': 'repeat-one',
  'trash.fill': 'delete',
  'eye.fill': 'visibility',
  'eye': 'visibility',
  'eye.slash': 'visibility-off',
  'pencil': 'edit',
  'line.3.horizontal': 'drag-handle',
  'square.grid.2x2': 'grid-view',
  'questionmark.circle.fill': 'help',
  'arrow.turn.down.right': 'subdirectory-arrow-right',
  'bookmark': 'bookmark-border',
  'bookmark.fill': 'bookmark',
  'flag.fill': 'flag',
  // Course-type, skill, and culture-category icons (replaced emoji-as-icons).
  'sunrise.fill': 'wb-twilight',
  'textformat.abc': 'abc',
  'basket.fill': 'shopping-basket',
  'sailboat.fill': 'sailing',
  'bubble.left.fill': 'chat',
  'building.2.fill': 'location-city',
  'music.note': 'music-note',
  'paintpalette.fill': 'palette',
  'puzzlepiece.fill': 'extension',
  'mappin': 'place',
  'figure.child': 'child-care',
  'party.popper.fill': 'celebration',
  'sparkles': 'auto-awesome',
  'tshirt.fill': 'checkroom',
  'fork.knife': 'restaurant',
  'hand.wave.fill': 'waving-hand',
  'building.columns.fill': 'balance',
  'person.3.fill': 'family-restroom',
  'moon.stars.fill': 'nights-stay',
  'theatermasks.fill': 'theater-comedy',
  'number.square.fill': 'calculate',
  'map.fill': 'map',
  'film.fill': 'movie',
  // Symbols that were in use across the app but had no entry here, so they
  // rendered as blank space on Android and web until this was filled in.
  'plus.circle.fill': 'add-circle',
  'trash': 'delete-outline',
  'globe': 'language',
  'bolt.fill': 'bolt',
  'brain.head.profile': 'psychology',
  'clock.arrow.circlepath': 'history',
  'rectangle.grid.2x2': 'grid-view',
  'stop.fill': 'stop',
  'arrow.clockwise': 'refresh',
  'camera.fill': 'photo-camera',
  'speaker.wave.3.fill': 'volume-up',
  'book.closed.fill': 'menu-book',
  'square.grid.3x3.fill': 'apps',
  'text.alignleft': 'format-align-left',
  'xmark.circle': 'cancel',
  'person.badge.plus': 'person-add',
  'key.fill': 'vpn-key',
  'doc.on.doc': 'content-copy',
  'arrow.left.arrow.right': 'swap-horiz',
  'pencil.and.scribble': 'draw',
  'point.topleft.down.curvedto.point.bottomright.up': 'account-tree',
  'lock': 'lock-outline',
  'mic': 'mic-none',
  'speaker.wave.2': 'volume-up',
  'minus': 'remove',
  'minus.circle': 'remove-circle-outline',
  'checkmark.circle': 'check-circle-outline',
  'equal': 'drag-handle',
  'arrow.up': 'north',
  'arrow.right': 'arrow-forward',
  'at': 'alternate-email',
  'target': 'crisis-alert',
  'checkmark.shield.fill': 'verified-user',
  'exclamationmark.bubble': 'feedback',
  'play.rectangle.fill': 'smart-display',
  'exclamationmark.triangle': 'warning-amber',
  'book.pages': 'auto-stories',
  'book.closed': 'menu-book',
  'books.vertical.fill': 'library-books',
  'questionmark.circle': 'help-outline',
  'doc.text': 'article',
  'square.and.pencil': 'edit-square',
  'star.circle.fill': 'stars',
  'tray.fill': 'inbox',
  'folder.fill': 'folder',
  'hand.tap': 'touch-app',
  'hand.tap.fill': 'touch-app',
  'hand.raised.fill': 'pan-tool',
  'moon.fill': 'dark-mode',
  'brain.fill': 'psychology',
  'quote.opening': 'format-quote',
  'medal.fill': 'military-tech',
  'megaphone.fill': 'campaign',
  'tortoise.fill': 'slow-motion-video',
  'slider.horizontal.3': 'tune',
  'paintpalette': 'palette',
  'bell.badge': 'notifications-active',
  'calendar.badge.plus': 'event',
  'record.circle': 'fiber-manual-record',
  'info.circle': 'info-outline',
  'pause.circle.fill': 'pause-circle',
  'stop.circle.fill': 'stop-circle',
  'gamecontroller.fill': 'sports-esports',
  'music.note.list': 'queue-music',
  'pencil.tip': 'edit',
  'list.number': 'format-list-numbered',
  'pawprint.fill': 'pets',
  'banknote': 'payments',
  'tag': 'label',
} satisfies IconMapping;

/** The SF Symbols this app can actually render on every platform. */
export type IconSymbolName = keyof typeof MAPPING;

/**
 * Narrows an arbitrary string to a renderable icon name. Only needed where the
 * value genuinely isn't known at compile time — server-supplied icons. Anywhere
 * else, type the config object's field as `IconSymbolName` instead of guarding.
 */
export function isIconSymbolName(value: string): value is IconSymbolName {
  return value in MAPPING;
}
