export type WebTourAudience = "all" | "admin" | "educator";

export interface WebTourDefinition {
  route: string;
  audience: WebTourAudience;
  mode: "spotlight" | "intro-card";
  title: string;
  description: string;
}

export const WEB_TOUR_REGISTRY = {
  welcome: {
    route: "/learn",
    audience: "all",
    mode: "intro-card",
    title: "Welcome to Beeli Web",
    description: "Get a quick walkthrough of navigation and core learning tools.",
  },
  learn: {
    route: "/learn",
    audience: "all",
    mode: "spotlight",
    title: "Learn",
    description: "Browse courses and continue lessons from where you paused.",
  },
  listen: {
    route: "/listen",
    audience: "all",
    mode: "spotlight",
    title: "Listen",
    description: "Practice listening with guided audio lessons.",
  },
  journal: {
    route: "/journal",
    audience: "all",
    mode: "spotlight",
    title: "Journal",
    description: "Capture reflections and track your language learning notes.",
  },
  feed: {
    route: "/feed",
    audience: "all",
    mode: "spotlight",
    title: "Feed",
    description: "Follow community activity and engage with other learners.",
  },
  quiz: {
    route: "/quiz",
    audience: "all",
    mode: "spotlight",
    title: "Quiz",
    description: "Test vocabulary and comprehension with interactive quiz flows.",
  },
  profile: {
    route: "/profile",
    audience: "all",
    mode: "spotlight",
    title: "Profile",
    description: "Review streaks, XP, and your overall progress.",
  },
  dashboard: {
    route: "/dashboard",
    audience: "all",
    mode: "intro-card",
    title: "Dashboard",
    description: "Analyze your learning trends and completion stats.",
  },
  settings: {
    route: "/settings",
    audience: "all",
    mode: "intro-card",
    title: "Settings",
    description: "Customize account preferences and app behavior.",
  },
  dictionary: {
    route: "/dictionary",
    audience: "all",
    mode: "intro-card",
    title: "Dictionary",
    description: "Search vocabulary and inspect usage details.",
  },
  wordReview: {
    route: "/word-review",
    audience: "all",
    mode: "intro-card",
    title: "Word Review",
    description: "Use spaced repetition to retain new vocabulary.",
  },
  contribute: {
    route: "/contribute",
    audience: "all",
    mode: "intro-card",
    title: "Contribute",
    description: "Submit new language content and audio contributions.",
  },
  myContributions: {
    route: "/my-contributions",
    audience: "all",
    mode: "intro-card",
    title: "My Contributions",
    description: "Track review status for your submitted entries.",
  },
  bounties: {
    route: "/bounties",
    audience: "all",
    mode: "intro-card",
    title: "Bounties",
    description: "Complete high-priority tasks to earn extra rewards.",
  },
  leaderboard: {
    route: "/leaderboard",
    audience: "all",
    mode: "intro-card",
    title: "Leaderboard",
    description: "See top learners and contribution rankings.",
  },
  battle: {
    route: "/battle",
    audience: "all",
    mode: "intro-card",
    title: "Battle",
    description: "Enter real-time competitive learning modes.",
  },
  battleLobby: {
    route: "/battle/lobby",
    audience: "all",
    mode: "intro-card",
    title: "Battle Lobby",
    description: "Match with opponents and prepare to start.",
  },
  battleQuiz: {
    route: "/battle/quiz",
    audience: "all",
    mode: "intro-card",
    title: "Battle Quiz",
    description: "Compete in timed quizzes against another learner.",
  },
  battleResults: {
    route: "/battle/results",
    audience: "all",
    mode: "intro-card",
    title: "Battle Results",
    description: "Review round outcomes and launch rematches.",
  },
  proverbs: {
    route: "/proverbs",
    audience: "all",
    mode: "intro-card",
    title: "Proverbs",
    description: "Explore culturally rich sayings by language.",
  },
  proverbsLanguage: {
    route: "/proverbs/[languageId]",
    audience: "all",
    mode: "intro-card",
    title: "Proverbs by Language",
    description: "Dive deeper into proverb meanings and context.",
  },
  cultural: {
    route: "/cultural",
    audience: "all",
    mode: "intro-card",
    title: "Cultural",
    description: "Learn language through stories, history, and context.",
  },
  culturalLanguage: {
    route: "/cultural/[languageId]",
    audience: "all",
    mode: "intro-card",
    title: "Cultural by Language",
    description: "Browse language-specific cultural modules.",
  },
  course: {
    route: "/course",
    audience: "all",
    mode: "intro-card",
    title: "Courses",
    description: "Discover available courses and entry points.",
  },
  courseDetail: {
    route: "/course/[id]",
    audience: "all",
    mode: "intro-card",
    title: "Course Detail",
    description: "Understand lessons, milestones, and progression.",
  },
  lessonDetail: {
    route: "/lesson/[id]",
    audience: "all",
    mode: "intro-card",
    title: "Lesson Detail",
    description: "Follow lesson media and transcript guidance.",
  },
  adminHome: {
    route: "/admin",
    audience: "admin",
    mode: "intro-card",
    title: "Admin Dashboard",
    description: "Monitor platform operations and moderation health.",
  },
  adminApplications: {
    route: "/admin/applications",
    audience: "admin",
    mode: "intro-card",
    title: "Admin Applications",
    description: "Review incoming reviewer and role applications.",
  },
  adminCourses: {
    route: "/admin/courses",
    audience: "admin",
    mode: "intro-card",
    title: "Admin Courses",
    description: "Manage course inventory and publishing controls.",
  },
  adminUsers: {
    route: "/admin/users",
    audience: "admin",
    mode: "intro-card",
    title: "Admin Users",
    description: "Manage user roles, access, and account issues.",
  },
  adminDictionary: {
    route: "/admin/dictionary",
    audience: "admin",
    mode: "intro-card",
    title: "Admin Dictionary",
    description: "Moderate dictionary quality and consistency.",
  },
  adminFeedback: {
    route: "/admin/feedback",
    audience: "admin",
    mode: "intro-card",
    title: "Admin Feedback",
    description: "Process user feedback and prioritize improvements.",
  },
  adminReview: {
    route: "/admin/review",
    audience: "admin",
    mode: "intro-card",
    title: "Admin Review",
    description: "Resolve high-priority moderation decisions.",
  },
  educatorHome: {
    route: "/educator",
    audience: "educator",
    mode: "intro-card",
    title: "Educator Dashboard",
    description: "Manage teaching workflows and classroom impact.",
  },
  educatorCourses: {
    route: "/educator/courses",
    audience: "educator",
    mode: "intro-card",
    title: "Educator Courses",
    description: "Create and organize lesson-ready course structures.",
  },
  educatorCourseDetail: {
    route: "/educator/courses/[id]",
    audience: "educator",
    mode: "intro-card",
    title: "Educator Course Detail",
    description: "Edit content sequencing and publishing status.",
  },
  educatorLessonEditor: {
    route: "/educator/courses/[id]/lessons/[lessonId]",
    audience: "educator",
    mode: "intro-card",
    title: "Educator Lesson Editor",
    description: "Refine lesson content and multimedia structure.",
  },
  educatorCulture: {
    route: "/educator/culture",
    audience: "educator",
    mode: "intro-card",
    title: "Educator Culture",
    description: "Curate culture-focused learning material.",
  },
  educatorDictionary: {
    route: "/educator/dictionary",
    audience: "educator",
    mode: "intro-card",
    title: "Educator Dictionary",
    description: "Maintain lexical quality and pedagogy alignment.",
  },
  educatorReview: {
    route: "/educator/review",
    audience: "educator",
    mode: "intro-card",
    title: "Educator Review",
    description: "Review classroom-relevant contributions and edits.",
  },
} as const;

export type WebTourId = keyof typeof WEB_TOUR_REGISTRY;